import type { Question } from "../schema";

export const calculationQuestions: Question[] = [
  {
    slug: "weight-based-dose-calculation",
    category: "calculation-data",
    formats: ["mmi"],
    difficulty: 2,
    question: "Calculate the dose and volume of medicine for a child, and check whether it is within the daily maximum.",
    stationBrief:
      "A child weighs 18 kg. 'Drug X' (a fictional medicine for this exercise) is prescribed at 15 mg/kg per dose, up to four times a day, with a maximum of 60 mg/kg per day. It comes as a liquid containing 120 mg in 5 mL. (1) What dose in mg should the child receive? (2) What volume in mL? (3) What is the maximum total daily dose? (4) The parent says they have already given 1,000 mg today. Can they give another dose? You have 5 minutes and no calculator.",
    whatIsBeingTested: "Accurate, calm arithmetic with units, checking your answer, and applying it safely — the kind of thinking behind safe prescribing.",
    followUps: [
      "Why do children's doses often depend on weight?",
      "What would you do if you weren't sure your answer was right?",
      "What checks exist in hospitals to prevent dosing errors?",
    ],
    scaffold: [
      { step: "Write down what you know", guidance: "Weight 18 kg; 15 mg/kg per dose; max 60 mg/kg/day; concentration 120 mg/5 mL." },
      { step: "Dose", guidance: "18 × 15 = 270 mg." },
      { step: "Volume", guidance: "120 mg in 5 mL → 24 mg/mL; 270 ÷ 24 = 11.25 mL." },
      { step: "Daily maximum", guidance: "18 × 60 = 1,080 mg per day." },
      { step: "Apply safely", guidance: "1,000 + 270 = 1,270 mg > 1,080 mg: do not give another full dose; seek advice." },
      { step: "Sanity check", guidance: "Does 11.25 mL seem reasonable? Re-check units and arithmetic aloud." },
    ],
    exemplar:
      "I'll write down what I know first: the child weighs 18 kg, the dose is 15 mg per kg, the maximum is 60 mg per kg per day, and the liquid is 120 mg in 5 mL.\n\nFirst, the dose: 18 times 15. 10 times 15 is 150, 8 times 15 is 120, so 270 mg per dose.\n\nSecond, the volume. 120 mg in 5 mL means 24 mg in each mL. So I need 270 divided by 24. 24 times 11 is 264, which leaves 6, and 6 is a quarter of 24 — so 11.25 mL. To check: 11.25 times 24 is 264 plus 6, which is 270. Good.\n\nThird, the maximum daily dose is 18 times 60, which is 1,080 mg.\n\nFinally, the parent has already given 1,000 mg. Another full dose would take the total to 1,270 mg, which is well over the 1,080 mg maximum. So they shouldn't give another dose. Only 80 mg remains within the limit, and in reality you wouldn't give an odd partial dose without advice — I'd tell them not to give any more for now and to speak to a pharmacist or doctor. I'd also want to check exactly what was given and when, in case they've made an error or used a different product.\n\nIn real life I'd always double-check a calculation like this with a colleague, because small errors with children can be serious.",
    annotations: [
      { excerpt: "I'll write down what I know first", note: "Organises information before calculating — reduces errors." },
      { excerpt: "10 times 15 is 150, 8 times 15 is 120", note: "Breaks mental arithmetic into manageable steps aloud." },
      { excerpt: "To check: 11.25 times 24", note: "Reverse-checks the answer — excellent safety habit." },
      { excerpt: "I'd want to check exactly what was given and when", note: "Moves beyond arithmetic to clinical safety thinking." },
    ],
    keyPoints: [
      "Dose 270 mg.",
      "Volume 11.25 mL (270 ÷ 24 mg/mL).",
      "Maximum 1,080 mg/day.",
      "Another dose would exceed the maximum — don't give; seek advice.",
      "Check your working and escalate uncertainty.",
    ],
    pitfalls: [
      "Unit errors (mg vs mL).",
      "Rushing and not checking.",
      "Giving the calculation but not answering the safety question.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["calculation", "prescribing-safety", "children"],
  },
  {
    slug: "iv-fluid-rate-calculation",
    category: "calculation-data",
    formats: ["mmi"],
    difficulty: 2,
    question: "Calculate the rate of an intravenous fluid infusion.",
    stationBrief:
      "A patient is prescribed 1 litre of fluid to run over 8 hours. (1) What rate in mL per hour should the pump be set to? (2) If no pump is available and a gravity giving set that delivers 20 drops per mL is used, how many drops per minute are needed? (3) After 3 hours, how much fluid should remain? You have 4 minutes.",
    whatIsBeingTested: "Unit conversion, rate calculations and practical checking.",
    followUps: [
      "Why might it matter if fluids were given too fast?",
      "How would you check the infusion was running correctly?",
      "Which patients would be especially at risk from too much fluid?",
    ],
    scaffold: [
      { step: "Convert units", guidance: "1 litre = 1,000 mL." },
      { step: "mL per hour", guidance: "1,000 ÷ 8 = 125 mL/h." },
      { step: "Drops per minute", guidance: "125 mL/h × 20 drops/mL = 2,500 drops/h; ÷ 60 ≈ 41.7 ≈ 42 drops/min." },
      { step: "Remaining after 3 hours", guidance: "125 × 3 = 375 mL given; 1,000 − 375 = 625 mL remaining." },
      { step: "Practical safety", guidance: "Check against the prescription; monitor the patient; risks of fluid overload." },
    ],
    exemplar:
      "First, 1 litre is 1,000 mL. Over 8 hours, that's 1,000 divided by 8, which is 125 mL per hour. That's what I'd set the pump to.\n\nFor the gravity set: 125 mL per hour at 20 drops per mL is 125 times 20, which is 2,500 drops per hour. Divide by 60 to get per minute: 2,500 divided by 60. 60 times 40 is 2,400, leaving 100, and 100 divided by 60 is about 1.7. So about 41.7, which I'd round to 42 drops per minute.\n\nAfter 3 hours, 3 times 125 is 375 mL should have gone in, so 625 mL should be left in the bag.\n\nThat last calculation is actually a useful practical check — if you looked at the bag after 3 hours and there was much more or much less left, you'd know something was wrong.\n\nThis matters because giving fluid too quickly can cause fluid overload, especially in older patients or people with heart or kidney problems, where it can build up in the lungs. So I'd also want to check the patient themselves, not just the numbers.",
    annotations: [
      { excerpt: "1 litre is 1,000 mL", note: "Explicit unit conversion." },
      { excerpt: "which I'd round to 42 drops per minute", note: "Sensible rounding for a practical setting." },
      { excerpt: "a useful practical check", note: "Connects arithmetic to real monitoring." },
    ],
    keyPoints: [
      "125 mL/h.",
      "About 42 drops/min.",
      "625 mL remaining after 3 hours.",
      "Checking and clinical relevance.",
    ],
    pitfalls: [
      "Forgetting to convert litres to mL.",
      "Forgetting to divide by 60 for minutes.",
      "False precision (41.6666…).",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["calculation", "rates", "fluids"],
  },
  {
    slug: "vaccination-uptake-graph",
    category: "calculation-data",
    formats: ["mmi", "panel", "oxbridge"],
    difficulty: 3,
    question: "Interpret this data on childhood vaccine uptake and discuss what it might mean.",
    stationBrief:
      "Illustrative data (not official statistics). Percentage of children receiving the first dose of MMR vaccine by age 2 in a region:\n2014: 93%\n2016: 92%\n2018: 91%\n2020: 90%\n2022: 89%\n2024: 89%\n\nThe World Health Organization recommends 95% coverage to prevent measles outbreaks. In the same period, the number of measles cases in the region rose from 12 to 85. You have 6 minutes.",
    whatIsBeingTested: "Reading data accurately, quantifying trends, generating explanations and recognising limitations — including correlation vs causation.",
    followUps: [
      "Does this data prove falling vaccination caused the rise in measles?",
      "What additional data would you want?",
      "What interventions might increase uptake?",
    ],
    scaffold: [
      { step: "Describe", guidance: "What is measured, where, over what time; note illustrative data." },
      { step: "Quantify", guidance: "Uptake fell 4 percentage points (93% → 89%), plateauing 2022–24; consistently below 95%. Cases rose from 12 to 85 (about sevenfold)." },
      { step: "Explain", guidance: "Hesitancy/misinformation; access (GP appointments, pandemic disruption, deprivation); recording issues. Measles is highly contagious so small falls matter." },
      { step: "Caveat", guidance: "Association not causation; case numbers depend on imported cases and testing; regional averages hide local pockets; percentage points vs percent." },
      { step: "Implications", guidance: "Targeted outreach, reminders, trusted messengers, catch-up clinics." },
    ],
    exemplar:
      "This shows the percentage of children who'd had their first MMR dose by age two in one region, from 2014 to 2024 — and I note it's illustrative data.\n\nUptake fell steadily from 93% to 89% between 2014 and 2022, then levelled off. That's a drop of four percentage points, and it's been below the WHO's 95% target throughout. Over the same period, measles cases rose from 12 to 85 — roughly a sevenfold increase.\n\nThe trends fit together biologically: measles is extremely contagious, so even a few percentage points below 95% can leave enough susceptible children for outbreaks to spread. Possible reasons for the fall include vaccine hesitancy and misinformation, difficulties getting GP appointments, disruption during the pandemic around 2020, and lower uptake in more deprived communities.\n\nBut I'd be careful not to say this proves one caused the other. The number of cases also depends on things like travellers bringing measles in, and on how much testing was done. And a regional average of 89% could hide some neighbourhoods at 95% and others at 70% — outbreaks tend to happen in those pockets. I'd want local breakdowns, data on the ages of cases and whether they were vaccinated, and ideally surveys on why parents didn't vaccinate.\n\nIf I were advising, I'd target the areas with the lowest uptake — with reminders, catch-up clinics at convenient times, and trusted community members helping explain the vaccine.",
    annotations: [
      { excerpt: "I note it's illustrative data", note: "Reads the brief carefully — describes before interpreting." },
      { excerpt: "four percentage points", note: "Correctly uses percentage points rather than 'four percent'." },
      { excerpt: "I'd be careful not to say this proves", note: "Recognises the limits of correlational data." },
      { excerpt: "could hide some neighbourhoods", note: "Insight that averages can conceal local variation — very strong." },
    ],
    keyPoints: [
      "Accurate description and quantification.",
      "Percentage points vs percent.",
      "Plausible explanations linked to measles transmissibility.",
      "Correlation vs causation and hidden local variation.",
      "Further data and practical interventions.",
    ],
    pitfalls: [
      "Stating causation as fact.",
      "Misreading the numbers.",
      "Ignoring the WHO threshold.",
      "Blaming parents.",
    ],
    frameworks: [{ slug: "data-interpretation-dqec", primary: true }],
    reading: ["marmot-review"],
    tags: ["data-interpretation", "vaccination", "public-health"],
  },
  {
    slug: "screening-test-accuracy",
    category: "calculation-data",
    formats: ["mmi", "oxbridge", "panel"],
    difficulty: 4,
    question: "A new screening test is 90% sensitive and 95% specific. If a person tests positive, how likely are they to have the disease?",
    stationBrief:
      "A disease affects 1% of the population. A new screening test has a sensitivity of 90% (it correctly identifies 90% of people with the disease) and a specificity of 95% (it correctly identifies 95% of people without the disease). 10,000 people are screened. (1) How many true positives and false positives would you expect? (2) If someone tests positive, what is the chance they actually have the disease? (3) What does this mean for a screening programme? You have 6 minutes.",
    whatIsBeingTested: "Understanding sensitivity, specificity and positive predictive value, and the counter-intuitive effect of low prevalence — central to evidence-based medicine.",
    followUps: [
      "How would the answer change if the disease affected 20% of people?",
      "What harms can false positives cause?",
      "How would you explain a positive result to a patient?",
    ],
    scaffold: [
      { step: "Use natural numbers", guidance: "Of 10,000: 1% = 100 have the disease; 9,900 don't." },
      { step: "True and false negatives/positives", guidance: "90% of 100 = 90 true positives (10 missed). 5% of 9,900 = 495 false positives." },
      { step: "PPV", guidance: "90 ÷ (90 + 495) = 90 ÷ 585 ≈ 15%." },
      { step: "Interpret", guidance: "Most positives are false when prevalence is low; a positive screen needs confirmatory testing." },
      { step: "Implications", guidance: "Anxiety, further tests, overdiagnosis vs benefit of early detection; prevalence matters (targeted screening)." },
    ],
    exemplar:
      "I find it easiest to use actual numbers. Of 10,000 people, 1% — so 100 — have the disease, and 9,900 don't.\n\nOf the 100 with the disease, the test picks up 90%, so 90 true positives, and 10 are missed.\n\nOf the 9,900 without the disease, 95% correctly test negative, so 5% test positive by mistake. 5% of 9,900 is 495 false positives.\n\nSo altogether, 90 plus 495 is 585 positive results, of which only 90 are real. 90 out of 585 is roughly 15%. So if someone tests positive, there's only about a 15% chance they actually have the disease — even though the test sounds very accurate.\n\nThat seems surprising, but it's because the disease is rare: a small error rate applied to a large number of healthy people produces more false positives than there are true cases.\n\nFor a screening programme, that means a positive screening result shouldn't be treated as a diagnosis — people need a confirmatory test, and they need to be told that clearly so they aren't unnecessarily frightened. False positives cause anxiety, further tests and sometimes harm. It also suggests screening works better in higher-risk groups: if 20% of people had the disease, the proportion of positives that were real would be much higher.",
    annotations: [
      { excerpt: "I find it easiest to use actual numbers", note: "Natural frequencies make the problem tractable and easy to explain." },
      { excerpt: "roughly 15%", note: "Correct answer (≈15.4%) with sensible rounding." },
      { excerpt: "because the disease is rare", note: "Explains why — the key conceptual insight about prevalence." },
      { excerpt: "if 20% of people had the disease", note: "Anticipates the follow-up; could calculate it (PPV ≈ 82%) for full marks." },
    ],
    keyPoints: [
      "90 true positives; 495 false positives.",
      "PPV ≈ 15%.",
      "Low prevalence drives false positives.",
      "Positive screen ≠ diagnosis; confirmatory tests and clear communication.",
      "Higher prevalence raises PPV.",
    ],
    pitfalls: [
      "Answering '90%' (confusing sensitivity with PPV).",
      "Arithmetic errors with percentages of 9,900.",
      "Not interpreting the result.",
    ],
    frameworks: [{ slug: "data-interpretation-dqec", primary: true }, { slug: "thinking-aloud" }],
    reading: [],
    tags: ["statistics", "screening", "evidence-based-medicine"],
  },
  {
    slug: "relative-vs-absolute-risk",
    category: "calculation-data",
    formats: ["mmi", "panel"],
    difficulty: 3,
    question: "A drug advert claims it 'halves the risk of heart attack'. What does that actually mean for a patient?",
    stationBrief:
      "In a trial, 2 in every 100 people taking a placebo had a heart attack over five years, compared with 1 in every 100 people taking the new drug. The drug costs £400 per year and causes muscle aches in 5% of people. (1) Calculate the relative risk reduction, absolute risk reduction and number needed to treat. (2) How would you explain this to a patient deciding whether to take it? You have 6 minutes.",
    whatIsBeingTested: "Understanding risk statistics, recognising how framing influences decisions, and communicating risk honestly for shared decision-making.",
    followUps: [
      "Why might a company prefer to quote relative risk?",
      "How would the NNT change for a higher-risk patient?",
      "What else would a patient want to know before deciding?",
    ],
    scaffold: [
      { step: "Relative risk reduction", guidance: "From 2% to 1% = 50% relative reduction ('halves')." },
      { step: "Absolute risk reduction", guidance: "2% − 1% = 1 percentage point." },
      { step: "NNT", guidance: "1 ÷ 0.01 = 100 people treated for five years to prevent one heart attack." },
      { step: "Harms and costs", guidance: "5 in 100 get muscle aches; cost per heart attack prevented (100 × £400 × 5 years = £200,000)." },
      { step: "Communicate", guidance: "Natural frequencies; balance benefit and harm; patient's own risk and values; shared decision." },
    ],
    exemplar:
      "The heart attack rate went from 2 in 100 to 1 in 100. In relative terms that's a 50% reduction — so 'halves the risk' is technically true.\n\nBut the absolute reduction is only 1 percentage point: from 2% to 1%. The number needed to treat is 1 divided by 0.01, which is 100. So 100 people would need to take the drug for five years for one of them to avoid a heart attack. The other 99 wouldn't have had one anyway, or would have one despite the drug.\n\nAgainst that, 5 in every 100 people get muscle aches. And cost-wise, 100 people for five years at £400 a year is £200,000 per heart attack prevented — which matters for the NHS, though it would also depend on how serious and costly the heart attacks prevented are.\n\nTo a patient, I'd explain it with the same numbers: 'Out of 100 people like you who take this for five years, about one will avoid a heart attack because of it, and about five will get muscle aches.' I'd ask what matters most to them — how worried they are about a heart attack, how they'd feel about side effects, and taking a daily tablet. Someone at higher risk would benefit more, so the numbers would look different for them.\n\nA company might prefer 'halves the risk' because it sounds much more impressive — which is why doctors need to look at the absolute figures.",
    annotations: [
      { excerpt: "technically true", note: "Acknowledges the claim before unpacking it — fair and precise." },
      { excerpt: "number needed to treat is 1 divided by 0.01, which is 100", note: "Correct calculation shown clearly." },
      { excerpt: "Out of 100 people like you", note: "Natural frequencies — the most understandable way to communicate risk." },
      { excerpt: "Someone at higher risk would benefit more", note: "Understands that absolute benefit depends on baseline risk." },
    ],
    keyPoints: [
      "RRR 50%, ARR 1 percentage point, NNT 100.",
      "Harms: 5 in 100 with muscle aches.",
      "Framing effect of relative risk.",
      "Natural-frequency communication and shared decision-making.",
      "Baseline risk changes absolute benefit.",
    ],
    pitfalls: [
      "Confusing relative and absolute risk.",
      "Ignoring harms and cost.",
      "Telling the patient what to do rather than helping them decide.",
    ],
    frameworks: [{ slug: "data-interpretation-dqec", primary: true }, { slug: "chunk-and-check" }],
    reading: ["gmc-decision-making-consent", "montgomery-consent"],
    tags: ["statistics", "risk-communication", "shared-decision-making"],
  },
];
