import type { Question } from "../schema";

export const communicationQuestions: Question[] = [
  {
    slug: "role-play-lost-laptop",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 3,
    question: "Role-play: tell your friend that you have lost the laptop they lent you.",
    stationBrief:
      "Your friend Sam lent you their laptop for the weekend. You left it on a train on Saturday. You have reported it to lost property, but it has not been handed in. Sam has a coursework deadline in five days and much of their work was saved only on the laptop. Sam is about to arrive. You have 6 minutes.",
    whatIsBeingTested: "Breaking bad news, honesty and taking responsibility, empathy with strong emotion, and agreeing a constructive plan.",
    followUps: [
      "(After the station) How do you think that went?",
      "What would you do differently if you did it again?",
      "How is this similar to a doctor telling a patient about a mistake?",
    ],
    scaffold: [
      { step: "Setting", guidance: "Greet Sam, sit down, check it's a good time." },
      { step: "Warning shot", guidance: "'I'm really sorry, I've got some bad news about your laptop.'" },
      { step: "Knowledge", guidance: "Explain clearly and honestly what happened, without excuses." },
      { step: "Emotion", guidance: "Pause; acknowledge anger or panic; apologise sincerely; don't argue." },
      { step: "Plan", guidance: "Offer concrete help: replacement, help recovering files (cloud backup, email, school system), telling the teacher about the deadline." },
      { step: "Close", guidance: "Summarise, check how they're feeling, agree when you'll next speak." },
    ],
    exemplar:
      "[Candidate stands to greet Sam, gestures to sit.]\n\n\"Hi Sam, thanks for coming. Have you got a few minutes? I need to talk to you about something important.\"\n\n\"I'm really sorry — I've got some bad news about your laptop.\" [Pause.] \"On Saturday I was on the train back from my aunt's and I left it on the luggage rack. I realised as soon as I got off. I reported it to lost property straight away and I've called every day since, but it hasn't been handed in.\"\n\n[Sam reacts angrily: 'Are you serious? My whole coursework is on there!']\n\n\"I know — I'm so sorry. You've got every right to be angry. I know how much work you've put into that coursework, and the deadline's on Friday.\" [Pause, lets Sam speak.]\n\n\"I want to do everything I can to put this right. First, I'll pay for a replacement laptop — I've already looked at getting the same model. Second, can we check whether any of your work is saved somewhere else — have you emailed any drafts to yourself or saved anything to the school system? I'll help you go through it tonight. And if the deadline's still a problem, I'll come with you to explain to your teacher that it was my fault, so you're not penalised for something I did.\"\n\n\"How are you feeling about that? … Is there anything else you need from me right now?\"\n\n\"I really am sorry, Sam. I'll message you tonight once I've heard back from lost property again, and let's meet tomorrow to work through the files.\"",
    annotations: [
      { excerpt: "I've got some bad news about your laptop.\" [Pause.]", note: "Warning shot followed by a pause — lets Sam prepare." },
      { excerpt: "You've got every right to be angry", note: "Validates the emotion instead of defending or minimising." },
      { excerpt: "I'll come with you to explain to your teacher", note: "Takes responsibility through action — the strongest part of the plan." },
      { excerpt: "Is there anything else you need from me right now?", note: "Checks the other person's needs before closing. Could leave more silence earlier on." },
    ],
    keyPoints: [
      "Warning shot and clear, honest explanation.",
      "Sincere apology without excuses.",
      "Acknowledge and sit with the emotion.",
      "Concrete plan to put things right.",
      "Summary and follow-up.",
    ],
    pitfalls: [
      "Blurting it out or burying it in excuses.",
      "Minimising ('it's only a laptop').",
      "Arguing back when Sam is angry.",
      "Leaving without a plan.",
    ],
    frameworks: [{ slug: "spikes", primary: true }, { slug: "de-escalation" }],
    reading: ["bawa-garba-and-candour"],
    tags: ["role-play", "breaking-bad-news", "apology", "candour"],
  },
  {
    slug: "role-play-angry-relative",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 3,
    question: "Role-play: calm an angry relative in the Emergency Department.",
    stationBrief:
      "You are a medical student in the Emergency Department. Mr Hughes's 82-year-old father has been waiting four hours on a trolley with hip pain after a fall. Mr Hughes approaches you, shouting that nobody is doing anything. You do not know the details of his father's care, but you can find the nurse in charge. You have 6 minutes.",
    whatIsBeingTested: "De-escalation, empathy, honesty about your role, professionalism under pressure and knowing when to involve others.",
    followUps: [
      "What would you have done if he had become physically threatening?",
      "Why do you think he was so angry?",
      "Should he be told how to make a formal complaint?",
    ],
    scaffold: [
      { step: "Stay calm and safe", guidance: "Open posture, calm voice, keep a safe distance; introduce yourself and your role honestly." },
      { step: "Listen", guidance: "Let him speak without interrupting." },
      { step: "Acknowledge and apologise", guidance: "Name his worry and frustration; apologise for the wait." },
      { step: "Explain honestly", guidance: "You're a student and don't know the details, but you can get the right person; explain triage briefly." },
      { step: "Act and agree", guidance: "Offer to fetch the nurse in charge now; commit to coming back by a set time; mention PALS/complaints if he wishes." },
    ],
    exemplar:
      "\"Hello, my name's Aisha, I'm a medical student working in the department today. I can see you're really upset — can you tell me what's happened?\"\n\n[Mr Hughes explains loudly; candidate listens, nodding, without interrupting.]\n\n\"So your dad fell this morning, he's in a lot of pain with his hip, and you've been waiting four hours without anyone telling you what's happening. That sounds really frightening, and I'm sorry it's been so long.\"\n\n[Mr Hughes: 'Nobody cares! He's 82!']\n\n\"I can hear how worried you are about him. I want to be honest with you — I'm a student, so I don't know the details of your dad's care and I can't make decisions about it. But I can go and get the nurse in charge right now, so someone who knows his care can talk to you and check his pain.\"\n\n\"The department is very busy today, and people are seen in order of how urgent their condition is — which I know is really frustrating when it's your dad who's in pain.\"\n\n\"Is there anything he needs right now — a drink, a blanket? I'll check with the nurse whether he's allowed anything to eat or drink.\"\n\n\"I'll come back within ten minutes, either with the nurse or with an update. And if you'd like to raise a concern formally afterwards, the hospital's Patient Advice and Liaison Service can help — I can get you the details.\"",
    annotations: [
      { excerpt: "can you tell me what's happened?", note: "Opens with an invitation to speak — lets anger discharge." },
      { excerpt: "So your dad fell this morning", note: "Summarises back — shows he has been heard." },
      { excerpt: "I want to be honest with you — I'm a student", note: "Honest about role and limits; doesn't overpromise." },
      { excerpt: "I'll come back within ten minutes", note: "Specific, achievable commitment. Checking with the nurse before offering food or drink is exactly right, as the patient may need surgery." },
    ],
    keyPoints: [
      "Calm, safe, open body language.",
      "Listen and summarise.",
      "Acknowledge emotion and apologise for the experience.",
      "Honesty about your role.",
      "Concrete action, timescale and complaint route.",
    ],
    pitfalls: [
      "Defending the hospital immediately.",
      "Blaming staff.",
      "Promising he'll be seen soon.",
      "Giving food or drink without checking (surgery may be needed).",
    ],
    frameworks: [{ slug: "de-escalation", primary: true }, { slug: "ice" }],
    reading: ["nhs-constitution"],
    tags: ["role-play", "de-escalation", "emergency-department"],
  },
  {
    slug: "explain-asthma-inhaler",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 2,
    question: "Role-play: explain to a 14-year-old recently diagnosed with asthma what asthma is and how to use their two inhalers.",
    stationBrief:
      "Jordan, 14, has just been diagnosed with asthma. They have a blue reliever inhaler (salbutamol) and a brown preventer inhaler (a steroid). Jordan plays football and is worried they will have to stop. They don't really understand why they need two inhalers. You have 6 minutes. (You are not expected to know detailed medical facts — use the information given.)",
    whatIsBeingTested: "Explaining clearly without jargon, adapting to a young person, checking understanding and addressing their concern.",
    followUps: [
      "How did you check that Jordan understood?",
      "What would you do if Jordan said they'd stop using the brown inhaler because they felt fine?",
      "How would your explanation change for a seven-year-old?",
    ],
    scaffold: [
      { step: "Start where they are", guidance: "What do they know? What worries them? (Football.)" },
      { step: "Explain asthma simply", guidance: "Sensitive airways that tighten and swell when triggered; analogy (narrow straw)." },
      { step: "Two inhalers", guidance: "Blue = quick relief when tight; brown = daily prevention of swelling, works only if taken regularly." },
      { step: "Address the concern", guidance: "With good control most people keep playing sport; reliever before exercise if advised." },
      { step: "Teach-back and safety-net", guidance: "Ask them to explain back; when to get help." },
    ],
    exemplar:
      "\"Hi Jordan, I'm Ben. I've been asked to chat to you about your asthma and your inhalers. Before I start, what do you already know about it — and is there anything you're worried about?\"\n\n[Jordan: 'Not much. I'm worried I'll have to stop football.']\n\n\"That's a really good thing to tell me, and I'll come back to it. So — the tubes that carry air into your lungs are called airways. In asthma, they're more sensitive than usual. When they meet a trigger — like cold air, pollen or sometimes exercise — the muscles around them tighten and the lining swells. It's a bit like trying to breathe through a narrow straw. That's why you feel tight and wheezy. Does that make sense so far?\"\n\n\"You've got two inhalers because they do different jobs. The blue one is your reliever. It relaxes those tight muscles quickly — within minutes — so you use it when you feel tight or wheezy. The brown one is your preventer. It calms down the swelling in your airways over time, so they're less likely to tighten in the first place. The tricky thing is it only works if you take it every day, even when you feel fine.\"\n\n\"About football — lots of top athletes have asthma. If the preventer keeps your airways calm, most people can keep playing. The doctor may tell you to use your blue inhaler before training — it's worth asking them.\"\n\n\"Just so I know I've explained it well, could you tell me which inhaler you'd use if you felt wheezy at football, and which one you take every day?\"\n\n[Jordan answers correctly.]\n\n\"Perfect. And if your blue inhaler ever isn't helping, or you're struggling to breathe or talk, that's an emergency and you should get help straight away.\"",
    annotations: [
      { excerpt: "is there anything you're worried about?", note: "Elicits the concern early so the explanation can address it." },
      { excerpt: "like trying to breathe through a narrow straw", note: "Relatable analogy for a teenager." },
      { excerpt: "could you tell me which inhaler you'd use", note: "Teach-back rather than 'does that make sense?' — the gold standard." },
      { excerpt: "that's an emergency", note: "Safety-netting — essential in any health explanation." },
    ],
    keyPoints: [
      "Explore knowledge and concerns first.",
      "Plain language and an analogy.",
      "Clear distinction between reliever and preventer.",
      "Address the football worry.",
      "Teach-back and safety-netting.",
    ],
    pitfalls: [
      "Jargon (bronchoconstriction, corticosteroid).",
      "Talking to them like a small child or like a colleague.",
      "Not addressing their worry.",
      "Inventing detailed dosing information.",
    ],
    frameworks: [{ slug: "chunk-and-check", primary: true }, { slug: "ice" }],
    reading: [],
    tags: ["role-play", "explaining", "young-people", "asthma"],
  },
  {
    slug: "role-play-patient-stopped-medication",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 3,
    question: "Role-play: a patient has stopped taking their blood pressure tablets. Find out why and discuss it with them.",
    stationBrief:
      "Mrs Patel, 58, was started on a tablet for high blood pressure three months ago. At a check-up, she says she stopped taking it six weeks ago. You are a medical student asked to find out why. (She stopped because she feels well, heard from a friend that the tablets damage your kidneys, and would prefer to try diet and exercise.) You have 6 minutes.",
    whatIsBeingTested: "Patient-centred communication: exploring ideas, concerns and expectations; respecting autonomy; sharing information and reaching a shared plan.",
    followUps: [
      "What if she still refused to take them?",
      "Why do you think so many people stop taking long-term medicines?",
      "Is it ever right to try to persuade a patient?",
    ],
    scaffold: [
      { step: "Open non-judgementally", guidance: "'Can you tell me a bit about how things have been with the tablets?'" },
      { step: "Ideas", guidance: "Why she thinks she doesn't need them." },
      { step: "Concerns", guidance: "The kidney worry and any side effects." },
      { step: "Expectations", guidance: "Her preference for lifestyle changes." },
      { step: "Share information", guidance: "High blood pressure is often symptomless; honest, balanced information about benefits and risks; lifestyle is a valuable part of treatment." },
      { step: "Shared plan", guidance: "Options, respect her decision, arrange follow-up with the doctor; don't prescribe or give specific medical advice as a student." },
    ],
    exemplar:
      "\"Hello Mrs Patel, I'm Tom, a medical student. The doctor mentioned you'd stopped your blood pressure tablets a while ago. I'm not here to tell you off — I'd just like to understand how things have been. Could you tell me a bit about it?\"\n\n[Mrs Patel: 'I just feel fine, so I didn't see the point.']\n\n\"That makes sense — why take a tablet if you feel well? Was there anything else that made you decide to stop?\"\n\n[Mrs Patel: 'My friend said they damage your kidneys.']\n\n\"That sounds like it's been worrying you. Is there anything else you're concerned about? … And what would you like to happen with your blood pressure?\"\n\n[Mrs Patel: 'I'd rather try diet and walking.']\n\n\"Thank you, that's really helpful. Can I share a couple of things? High blood pressure usually doesn't cause any symptoms, which is why it's sometimes called silent — but over years it can strain the heart, kidneys and blood vessels, which is why doctors treat it even when people feel fine.\"\n\n\"On the kidney worry — I'm a student, so the doctor would be the best person to explain the details for your particular tablet. What I do know is that untreated high blood pressure is itself one of the common causes of kidney damage, and doctors usually do blood tests to check kidney function while people are on these tablets.\"\n\n\"Diet and exercise are a really good idea and can lower blood pressure — they're part of treatment either way. Would it help if I asked the doctor to talk through your options with you, including whether trying lifestyle changes with close monitoring is an option?\"\n\n[Agrees.] \"Great. I'll let the doctor know what we've discussed.\"",
    annotations: [
      { excerpt: "I'm not here to tell you off", note: "Removes judgement — makes honest disclosure more likely." },
      { excerpt: "Was there anything else", note: "Keeps exploring — the real concern (kidneys) often comes second." },
      { excerpt: "I'm a student, so the doctor would be the best person", note: "Stays within competence while still giving useful, accurate information." },
      { excerpt: "they're part of treatment either way", note: "Validates her preference — shared decision-making, not persuasion." },
    ],
    keyPoints: [
      "Non-judgemental opening.",
      "Ideas, concerns and expectations explored and responded to.",
      "Balanced information within your competence.",
      "Respect for her autonomy.",
      "Shared next step with the doctor.",
    ],
    pitfalls: [
      "Lecturing or scaring her.",
      "Dismissing her friend's view as 'rubbish'.",
      "Giving specific prescribing advice as a student.",
      "Ignoring her lifestyle preference.",
    ],
    frameworks: [{ slug: "ice", primary: true }, { slug: "chunk-and-check" }],
    reading: ["gmc-decision-making-consent"],
    tags: ["role-play", "adherence", "shared-decision-making"],
  },
  {
    slug: "explain-blood-test-to-child",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 3,
    question: "Role-play: a 7-year-old is frightened about having a blood test. Help them understand what will happen.",
    stationBrief:
      "Lily, 7, needs a blood test today. She is sitting with her mum and is tearful, saying she doesn't want a needle. You are a medical student. The nurse will take the blood; your job is to help Lily understand and feel less frightened. You have 6 minutes.",
    whatIsBeingTested: "Communicating with a child at her level, honesty, involving the parent, and building trust without false reassurance.",
    followUps: [
      "Why shouldn't you tell a child 'it won't hurt'?",
      "What would you do if she still refused?",
      "How is consent different for a young child?",
    ],
    scaffold: [
      { step: "Get to her level", guidance: "Sit down, introduce yourself simply, talk to Lily as well as Mum." },
      { step: "Find out her worry", guidance: "What is she scared of? Has she had one before?" },
      { step: "Honest, simple explanation", guidance: "Why (to help the doctors find out how to make her better), what (a tiny scratch, a few seconds), who (nurse and Mum there)." },
      { step: "Give her some control", guidance: "Choices: which arm, sit on Mum's lap, look away or watch, a distraction, cream to numb if available." },
      { step: "Praise and reassure honestly", guidance: "It's OK to be scared; you'll be brave together; sticker afterwards." },
    ],
    exemplar:
      "[Candidate sits down at Lily's height.]\n\n\"Hi Lily, I'm Priya. I'm learning to be a doctor. Is it OK if I sit with you and your mum for a bit?\"\n\n\"You look a bit worried. Can you tell me what you're worried about?\"\n\n[Lily: 'I don't want the needle. It's going to hurt.']\n\n\"That's OK — lots of people feel scared about needles, even grown-ups. Can I tell you what's going to happen, so there are no surprises?\"\n\n\"The doctors want to look at a tiny bit of your blood, to help them find out how to make you feel better. The nurse will put a band round your arm, and then there'll be a sharp scratch — like a quick pinch — for a few seconds. Then it's done. I'm not going to tell you it won't feel like anything, because it might a little bit, but it's very quick.\"\n\n\"And you get to choose some things. Would you like to sit on Mummy's lap? Would you like to look away, or watch? Some children like to count to ten with their mum, or blow bubbles — what would you like to do?\"\n\n[Lily chooses to sit on Mum's lap and count.]\n\n\"That's a brilliant plan. And Mum, it really helps if you stay calm and hold her in a cuddle.\"\n\n\"I think you're being really brave for asking questions. Shall we tell the nurse your plan?\"",
    annotations: [
      { excerpt: "Candidate sits down at Lily's height", note: "Non-verbal communication matters as much as words with children." },
      { excerpt: "I'm not going to tell you it won't feel like anything", note: "Honesty builds trust — false reassurance damages it for next time." },
      { excerpt: "you get to choose some things", note: "Giving control reduces fear — a key paediatric communication technique." },
      { excerpt: "Mum, it really helps if you stay calm", note: "Involves the parent practically." },
    ],
    keyPoints: [
      "Physical level and simple language.",
      "Explore the specific fear.",
      "Honest explanation — no 'it won't hurt'.",
      "Choices and distraction to give control.",
      "Involve the parent; praise effort.",
    ],
    pitfalls: [
      "Talking only to the parent.",
      "False reassurance.",
      "Medical jargon.",
      "Pressuring or rushing her.",
    ],
    frameworks: [{ slug: "chunk-and-check", primary: true }, { slug: "ice" }],
    reading: ["gillick-fraser"],
    tags: ["role-play", "children", "explaining", "anxiety"],
  },
  {
    slug: "role-play-friend-struggling",
    category: "role-play-communication",
    formats: ["mmi"],
    difficulty: 3,
    question: "Role-play: your friend has seemed withdrawn and has stopped coming to lessons. Talk to them.",
    stationBrief:
      "Your friend Alex has missed several lessons in the last two weeks, has stopped replying to group chats and looks tired. You have decided to talk to Alex at lunch. (Alex is stressed about exams and family problems at home, and has been sleeping badly. There are no immediate safety concerns unless the candidate asks directly, in which case Alex says they are not having thoughts of harming themselves.) You have 6 minutes.",
    whatIsBeingTested: "Sensitive, non-judgemental communication, active listening, recognising when and how to encourage help, and respecting a friend's autonomy.",
    followUps: [
      "What would you have done if Alex had said they were thinking of harming themselves?",
      "Would you tell a teacher even if Alex asked you not to?",
      "How do you look after yourself when supporting a friend?",
    ],
    scaffold: [
      { step: "Open gently", guidance: "Private setting; express care, not criticism: 'I've noticed you've not been yourself — how are you doing?'" },
      { step: "Listen", guidance: "Open questions; allow silence; reflect back; don't rush to fix." },
      { step: "Explore", guidance: "Sleep, stress, support; ask directly and calmly about safety if concerned." },
      { step: "Encourage support", guidance: "Trusted adult, school counsellor, GP; offer to go with them." },
      { step: "Confidentiality limits", guidance: "Be honest that if you were worried about their safety, you'd need to tell someone." },
      { step: "Close", guidance: "Agree a small next step and check in again." },
    ],
    exemplar:
      "\"Hey Alex, have you got a minute? I've noticed you've not been in lessons much, and you've been a bit quiet. I'm not having a go — I just wanted to check how you're doing.\"\n\n[Alex shrugs: 'I'm fine.']\n\n\"OK. It's just you seem really tired, and it's not like you to miss things. I'm here if you want to talk — no pressure.\" [Pause.]\n\n[Alex: 'Things are just a lot at the moment. Exams, and stuff at home.']\n\n\"That sounds really hard, dealing with both at once. Do you want to tell me a bit more about it?\" [Listens.] \"How's your sleep been?\"\n\n[Alex: 'Rubbish. I lie awake worrying.']\n\n\"I'm really glad you told me. Can I ask — sometimes when people are feeling this low, they have thoughts of hurting themselves. Have you had any thoughts like that?\"\n\n[Alex: 'No, nothing like that.']\n\n\"OK, thank you for being honest. I think it might help to talk to someone who can actually do something about the exam pressure and the stuff at home — maybe Ms Rahman, the pastoral lead, or your GP about the sleep. Would you want me to come with you?\"\n\n[Alex agrees to see the pastoral lead.]\n\n\"Great. I'll keep this between us, but I want to be honest — if I was ever worried you weren't safe, I'd have to tell someone, because I care about you. Shall we go together tomorrow at break? And I'll message you tonight.\"",
    annotations: [
      { excerpt: "I'm not having a go", note: "Removes blame — makes it easier to open up." },
      { excerpt: "no pressure.\" [Pause.]", note: "Uses silence rather than pushing — often what lets someone speak." },
      { excerpt: "Have you had any thoughts like that?", note: "Asks directly and calmly about safety. Asking does not increase risk, and it is the right thing to do." },
      { excerpt: "if I was ever worried you weren't safe, I'd have to tell someone", note: "Honest about confidentiality limits — mirrors the professional approach." },
    ],
    keyPoints: [
      "Private, caring, non-judgemental opening.",
      "Active listening and silence.",
      "Direct, calm safety question when appropriate.",
      "Encourage professional support; offer to accompany.",
      "Honest limits of confidentiality; follow-up.",
    ],
    pitfalls: [
      "Lecturing about missing lessons.",
      "Jumping to solutions without listening.",
      "Promising total secrecy.",
      "Avoiding the safety question out of awkwardness.",
    ],
    frameworks: [{ slug: "ice", primary: true }, { slug: "de-escalation" }],
    reading: ["gmc-confidentiality"],
    tags: ["role-play", "mental-health", "listening", "confidentiality"],
  },
];
