import type { Question } from "../schema";

export const motivationQuestions: Question[] = [
  {
    slug: "why-medicine",
    category: "motivation-insight",
    formats: ["mmi", "panel", "online"],
    difficulty: 2,
    question: "Why do you want to be a doctor?",
    whatIsBeingTested:
      "Whether your motivation is genuine, specific and informed by a realistic understanding of the job — and whether you can explain why doctor, rather than another healthcare role.",
    followUps: [
      "Why not nursing, pharmacy or physiotherapy?",
      "What was the most difficult thing you saw during your work experience?",
      "What will you find hardest about being a doctor?",
      "If you could not study medicine, what would you do instead?",
    ],
    scaffold: [
      { step: "Motivation", guidance: "Name one or two specific drivers. Avoid 'I want to help people' unless you immediately make it concrete." },
      { step: "Evidence", guidance: "One moment that tested or confirmed this — something you saw, did or read. Be specific and anonymous." },
      { step: "Insight", guidance: "Show you understand what doctors specifically do (diagnosis, decisions under uncertainty, leadership of care) and the realities — pressure, uncertainty, emotional load." },
      { step: "Fit", guidance: "Link to qualities you've shown and end on a forward-looking line. Aim for 90 seconds." },
    ],
    exemplar:
      "I'm drawn to medicine because it combines two things I care about: working through problems scientifically, and being responsible for helping a particular person through something difficult.\n\nThe moment that made this concrete was shadowing on a stroke ward. A registrar had to explain to a family why their father couldn't safely eat and would need a feeding tube. The clinical decision had been made quickly from the swallowing assessment, but the conversation took twenty minutes — she checked what they'd understood, sat through a long silence, and changed her explanation when the daughter looked confused. I realised the diagnosis was only part of the job; turning it into a decision a family could live with was the skill.\n\nI also saw the harder side: she was holding a long list of patients, the family were understandably upset, and she was making a decision without a perfect answer. That's what distinguishes the doctor's role for me — being the person who integrates the information and takes responsibility for the decision, while working closely with nurses and therapists who often know the patient better day to day.\n\nThat suits me. At school I've enjoyed biology most when I've had to apply it to a problem rather than memorise it, and tutoring younger students has taught me I like adapting an explanation until it lands. I know the training is long and the pressure is real, but that combination of reasoning and responsibility is what I want to spend my career doing.",
    annotations: [
      { excerpt: "working through problems scientifically, and being responsible for helping a particular person", note: "Specific motivation stated upfront — avoids the generic 'I want to help people'." },
      { excerpt: "the conversation took twenty minutes", note: "Concrete observation that shows what the student actually noticed, not just where they went." },
      { excerpt: "being the person who integrates the information and takes responsibility for the decision", note: "Answers the unspoken 'why not nursing?' by describing the doctor's distinct role without disparaging others." },
      { excerpt: "I know the training is long and the pressure is real", note: "Acknowledges downsides — credibility. Could be strengthened with one sentence on how they'd cope." },
    ],
    keyPoints: [
      "Specific motivation grounded in an experience you can describe vividly.",
      "Understanding of what distinguishes the doctor's role (diagnosis, clinical decision-making, responsibility, leadership).",
      "Realism about the challenges, and why you still want it.",
      "Evidence of qualities that fit — briefly, without listing.",
    ],
    pitfalls: [
      "Opening with 'I've always wanted to be a doctor' or 'my parents are doctors' without reflection.",
      "Reasons that apply equally to any caring profession.",
      "Listing every placement instead of reflecting deeply on one.",
      "Money, status or 'job security' as motivators.",
      "Sounding memorised — interviewers can tell.",
    ],
    frameworks: [{ slug: "why-medicine-meif", primary: true }, { slug: "what-so-what-now-what" }],
    reading: ["gmc-outcomes-for-graduates", "gmc-good-medical-practice"],
    tags: ["motivation", "role-of-doctor"],
  },
  {
    slug: "why-not-nursing",
    category: "motivation-insight",
    formats: ["mmi", "panel"],
    difficulty: 3,
    question: "If you want to care for patients, why not become a nurse or a physician assistant instead?",
    whatIsBeingTested:
      "Understanding of different roles in the multidisciplinary team, respect for colleagues, and clarity about what specifically draws you to the doctor's role.",
    followUps: [
      "What do nurses do that doctors don't?",
      "How would you feel if a nurse challenged one of your decisions?",
      "Physician assistants can take histories and examine patients — so what does a doctor add?",
    ],
    scaffold: [
      { step: "Respect first", guidance: "Open by recognising the value and expertise of nursing and other roles — avoid any hierarchy." },
      { step: "Distinguish the roles", guidance: "Nurses: holistic, continuous care and advocacy; own professional expertise. Doctors: diagnosis of undifferentiated problems, clinical decision-making under uncertainty, overall medical responsibility, prescribing, leading medical management." },
      { step: "Your pull", guidance: "Explain which part of the doctor's role specifically attracts you, with evidence." },
      { step: "Team insight", guidance: "Show you see roles as complementary — good care depends on all of them." },
    ],
    exemplar:
      "I'd start by saying I don't see nursing as a lesser version of medicine — it's a different profession with its own expertise. On my placement it was the nurses who noticed a patient becoming confused overnight and who knew how each person liked to be cared for. That continuity and advocacy are things doctors often can't provide.\n\nWhat draws me to medicine specifically is working out what's wrong when the answer isn't obvious — taking a patient with vague symptoms, forming a differential diagnosis, deciding which tests will actually change management, and taking responsibility for the plan. I saw a GP spend a consultation untangling whether a woman's tiredness was anaemia, depression, thyroid disease or simply a new baby, and the uncertainty and judgement involved really appealed to me.\n\nPhysician assistants can do parts of that work, but under the supervision of a doctor, and recent national recommendations are that they shouldn't see undifferentiated patients except within defined protocols. The doctor carries the overall responsibility for diagnosis and decisions, and that's the part I want to train for.\n\nUltimately I think the best care comes from these roles working together, each respecting the others' expertise — and I'd want to be the kind of doctor who listens when a nurse says 'something isn't right'.",
    annotations: [
      { excerpt: "I don't see nursing as a lesser version of medicine", note: "Leads with respect — the single most important move in this question." },
      { excerpt: "working out what's wrong when the answer isn't obvious", note: "Names a genuinely distinct feature of the doctor's role: diagnosis of undifferentiated presentations." },
      { excerpt: "recent national recommendations", note: "Shows current awareness (the Leng review) without turning the answer into a political debate." },
      { excerpt: "listens when a nurse says 'something isn't right'", note: "Strong close showing teamwork insight and humility." },
    ],
    keyPoints: [
      "Respect for all professions — no hierarchy language.",
      "Accurate distinction: diagnosis, decision-making, medical responsibility, prescribing, leadership of medical care.",
      "Personal evidence for why that distinction attracts you.",
      "Complementary roles and the value of teamwork.",
    ],
    pitfalls: [
      "Implying nurses are less intelligent or less important.",
      "Saying 'doctors earn more' or 'have more status'.",
      "Inaccurate claims (e.g. that nurses can't prescribe — many are independent prescribers).",
      "Disparaging physician assistants.",
    ],
    frameworks: [{ slug: "why-medicine-meif", primary: true }],
    reading: ["leng-review", "gmc-good-medical-practice"],
    tags: ["motivation", "role-of-doctor", "mdt"],
  },
  {
    slug: "downsides-of-medicine",
    category: "motivation-insight",
    formats: ["mmi", "panel", "online"],
    difficulty: 2,
    question: "What do you think are the biggest downsides of a career in medicine, and how would you cope with them?",
    whatIsBeingTested: "Realistic insight into the demands of medicine and evidence of self-awareness and healthy coping strategies.",
    followUps: [
      "How do you currently deal with stress?",
      "What would you do if you noticed a colleague was burning out?",
      "Is it acceptable for a doctor to put their own wellbeing first?",
    ],
    scaffold: [
      { step: "Name two or three real downsides", guidance: "E.g. emotional burden of illness and death, uncertainty and responsibility, long training and moving around, shift work, system pressures, risk of burnout." },
      { step: "Show how you know", guidance: "Evidence from work experience, conversations with doctors, or reading." },
      { step: "Coping strategies", guidance: "Specific, current strategies that already work for you, plus support structures in medicine (supervision, peer support, reflective practice)." },
      { step: "Why still worth it", guidance: "End by weighing the downsides against what draws you." },
    ],
    exemplar:
      "I think three things stand out. First, the emotional weight — seeing people at their most unwell and sometimes being unable to change the outcome. Second, responsibility under uncertainty: making decisions with incomplete information, knowing some will turn out wrong. Third, the practical side: long training, rotating jobs across a region, night shifts, and a system under a lot of pressure.\n\nI got a sense of this talking to a foundation doctor during my placement. She said the hardest part wasn't the hours but going home unsure whether she'd missed something. She coped by handing over properly, debriefing with her team after bad days, and protecting time for running.\n\nFor me, I already know that I cope best when I talk things through and keep up exercise — I play in a football team twice a week and I noticed during my exams that when I dropped it, I slept worse and got more anxious. I'd want to keep those habits and use the support that exists, like supervisors and peer groups, rather than seeing asking for help as weakness. Good Medical Practice actually expects doctors to look after their own health, which I think is right, because a burnt-out doctor is less safe.\n\nThose downsides are real, but they come from the same thing that attracts me — the responsibility of looking after people when it matters.",
    annotations: [
      { excerpt: "going home unsure whether she'd missed something", note: "Insight from a real conversation — much stronger than a generic list." },
      { excerpt: "when I dropped it, I slept worse", note: "Self-awareness backed by evidence rather than an abstract claim to be resilient." },
      { excerpt: "a burnt-out doctor is less safe", note: "Links wellbeing to patient safety — the professional argument, not just the personal one." },
      { excerpt: "come from the same thing that attracts me", note: "Nice turn, but make sure it doesn't sound rehearsed — deliver it naturally." },
    ],
    keyPoints: [
      "Specific, realistic downsides — emotional, cognitive and practical.",
      "Evidence of how you learned about them.",
      "Personal, already-tested coping strategies.",
      "Recognition that seeking support is professional, not weak.",
    ],
    pitfalls: [
      "Claiming there are no downsides or that stress doesn't affect you.",
      "Listing only pay or hours in a complaining tone.",
      "Coping strategies that are vague ('I'm resilient').",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }],
    reading: ["this-is-going-to-hurt", "gmc-good-medical-practice", "do-no-harm"],
    tags: ["motivation", "resilience", "wellbeing"],
  },
  {
    slug: "why-this-medical-school",
    category: "motivation-insight",
    formats: ["mmi", "panel"],
    difficulty: 2,
    question: "Why have you applied to this medical school?",
    whatIsBeingTested: "Whether you have researched the course and can link its specific features to how you learn and what you want — rather than reputation or location alone.",
    followUps: [
      "What do you know about how the course is taught here?",
      "What do you think will be the most challenging part of this course for you?",
      "What would you contribute to this medical school?",
    ],
    scaffold: [
      { step: "Two or three specific features", guidance: "Teaching style (tutorials/supervisions, case-based learning, integrated BSc), early clinical contact, patient population, research opportunities." },
      { step: "Link each to you", guidance: "Why that feature suits how you learn or what you want to develop — with evidence." },
      { step: "The population and place", guidance: "Who you would be treating and what that offers (diversity, inequalities, rural/urban)." },
      { step: "What you'd contribute", guidance: "One brief line — society, peer teaching, research interest." },
    ],
    exemplar:
      "I've applied here for three main reasons. The first is the way the course is taught. I learn best when I have to explain and defend my thinking — in my EPQ the most useful sessions were when my supervisor kept asking 'how do you know that?' — so small-group teaching, where you can't hide behind lecture notes, really appeals to me.\n\nSecond, the patient population. Your placements cover areas with very different levels of deprivation, and after reading the Marmot review I've become interested in how much health is shaped outside the hospital. Training somewhere I'd see that directly matters to me.\n\nThird, the research emphasis. I don't know yet whether I want an academic career, but having protected time to do a research project would let me find out properly rather than guessing.\n\nWhen I visited, what stood out was how the students described supporting each other — peer teaching schemes, for example. I've run a revision group for my biology class this year, and I'd like to be involved in something similar.",
    annotations: [
      { excerpt: "when my supervisor kept asking 'how do you know that?'", note: "Evidence for a learning preference — makes a generic course feature personal." },
      { excerpt: "after reading the Marmot review", note: "Connects the school's population to a genuine interest. Make sure the facts about the school's placements are accurate before you say this." },
      { excerpt: "I don't know yet whether I want an academic career", note: "Honest — better than overclaiming research ambitions." },
    ],
    keyPoints: [
      "Specific, accurate course features (check the school's own website).",
      "A personal reason each feature suits you.",
      "Awareness of the patient population and region.",
      "A brief note on what you would contribute.",
    ],
    pitfalls: [
      "Reputation, league tables or 'it's a good university' as the main reason.",
      "Inaccurate course details — interviewers know their course.",
      "Reasons that apply to every medical school.",
      "Location or nightlife as a main reason.",
    ],
    frameworks: [{ slug: "why-medicine-meif", primary: true }],
    reading: ["marmot-review"],
    tags: ["motivation", "why-this-school"],
  },
  {
    slug: "what-makes-a-good-doctor",
    category: "motivation-insight",
    formats: ["mmi", "panel", "online"],
    difficulty: 1,
    question: "What qualities make a good doctor, and which do you think is the most important?",
    whatIsBeingTested: "Insight into professional qualities, ability to prioritise and justify, and self-awareness about your own strengths and gaps.",
    followUps: [
      "Which of those qualities do you need to develop most?",
      "Can empathy be taught?",
      "Is it more important for a doctor to be kind or to be competent?",
    ],
    scaffold: [
      { step: "Name three or four qualities", guidance: "E.g. clinical competence, communication, empathy, integrity/honesty, teamwork, managing uncertainty, reflection." },
      { step: "Illustrate one or two", guidance: "Brief example from work experience of the quality in action." },
      { step: "Choose and justify the most important", guidance: "Commit to one and explain why; acknowledge they are interdependent." },
      { step: "Self-reflection", guidance: "Which you already show (with evidence) and which you are developing." },
    ],
    exemplar:
      "I'd say a good doctor needs competence, communication, integrity and the ability to work in a team — and underpinning all of them, self-awareness about their own limits.\n\nOn my placement I watched a consultant tell a junior colleague, in front of the team, 'I'm not sure — let's ask the renal team.' It showed both integrity and teamwork: admitting uncertainty rather than guessing, in a way that made it normal for everyone else to do the same.\n\nIf I had to choose one, I'd pick honesty. Patients have to trust that what their doctor tells them is true, colleagues need to trust you'll say when something's wrong, and without honesty, competence can become dangerous — the Mid Staffordshire inquiry showed what happens when problems aren't spoken about. That said, they're interdependent: honesty without good communication can be brutal, and kindness without competence doesn't help anyone.\n\nFor me, communication is a strength I've built through tutoring, but managing uncertainty is something I'm still developing. I tend to want a definite answer, so I've been deliberately practising problems without clear solutions — which I know will matter far more in medicine.",
    annotations: [
      { excerpt: "'I'm not sure — let's ask the renal team.'", note: "Observed behaviour illustrating two qualities at once — efficient and memorable." },
      { excerpt: "I'd pick honesty", note: "Commits to an answer and justifies it — many candidates list qualities and never choose." },
      { excerpt: "the Mid Staffordshire inquiry", note: "Relevant evidence, used briefly without derailing." },
      { excerpt: "managing uncertainty is something I'm still developing", note: "Genuine weakness with a concrete plan — shows self-awareness." },
    ],
    keyPoints: [
      "Range of qualities (clinical and non-clinical).",
      "Illustration from real observation.",
      "A clear choice with justification and acknowledgement of interdependence.",
      "Honest self-assessment.",
    ],
    pitfalls: [
      "Listing ten qualities without depth.",
      "Refusing to choose one.",
      "Claiming to already possess them all perfectly.",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }],
    reading: ["gmc-good-medical-practice", "gmc-outcomes-for-graduates", "francis-report"],
    tags: ["motivation", "qualities"],
  },
  {
    slug: "career-in-ten-years",
    category: "motivation-insight",
    formats: ["panel", "mmi"],
    difficulty: 2,
    question: "Where do you see yourself in ten to fifteen years, and what do you know about the path to get there?",
    whatIsBeingTested: "Understanding of UK medical training structure and realistic, open-minded career thinking.",
    followUps: [
      "What happens after medical school?",
      "Why might you change your mind about a specialty?",
      "What are the pros and cons of general practice versus a hospital specialty?",
    ],
    scaffold: [
      { step: "Show you know the pathway", guidance: "Medical school (5–6 years) → Foundation Programme (2 years, provisional then full GMC registration) → specialty or GP training (GP about 3 years; hospital specialties typically 5–8 years including core training) → consultant or GP." },
      { step: "An honest, open interest", guidance: "Something that currently interests you and why — but stay open." },
      { step: "Beyond clinical work", guidance: "Teaching, research, leadership, global health — whatever genuinely interests you." },
      { step: "Realism", guidance: "Competition for training posts, flexibility, life outside work." },
    ],
    exemplar:
      "In ten to fifteen years I'd hope to be finishing specialty training or recently qualified as a consultant or GP. The path would be medical school, then the two-year Foundation Programme, then either GP training, which is about three years, or core and specialty training in a hospital specialty, which usually takes longer.\n\nRight now I'm interested in paediatrics. At a special school where I volunteer, I've seen how much a child's condition shapes the whole family's life, and I like the idea of looking after a child's development over time rather than one episode. But I'm aware most people change their minds once they experience different specialties, and I want to keep an open mind — I could just as easily find I love general practice for the continuity.\n\nWhatever I do, I'd like teaching to be part of it. I've enjoyed tutoring, and I've noticed the doctors I admired most on placement took time to explain things to students.\n\nI also know training posts are competitive at the moment, which is part of why I'd want to use medical school to explore widely rather than lock in early.",
    annotations: [
      { excerpt: "the two-year Foundation Programme", note: "Accurate pathway knowledge, given briefly without turning into a lecture." },
      { excerpt: "I want to keep an open mind", note: "Balances a genuine interest with realistic openness." },
      { excerpt: "training posts are competitive", note: "Current awareness. Could briefly add why (the gap between graduate numbers and specialty training posts) if asked." },
    ],
    keyPoints: [
      "Accurate outline of UK training: Foundation Programme, specialty/GP training, consultant/GP.",
      "A genuine, evidenced interest held with an open mind.",
      "Interests beyond direct clinical care.",
      "Awareness of competition and flexibility.",
    ],
    pitfalls: [
      "Being fixed on one prestigious specialty ('I'm going to be a neurosurgeon').",
      "Not knowing what the Foundation Programme is.",
      "No idea at all — show some direction even if tentative.",
    ],
    frameworks: [{ slug: "why-medicine-meif", primary: true }],
    reading: ["gmc-outcomes-for-graduates"],
    tags: ["motivation", "career", "training-pathway"],
  },
];
