import type { Question } from "../schema";

export const nhsQuestions: Question[] = [
  {
    slug: "nhs-values",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel", "online"],
    difficulty: 1,
    question: "What are the values of the NHS, and which one do you think is most important?",
    whatIsBeingTested: "Knowledge of the NHS Constitution and the ability to connect values to real experience.",
    followUps: [
      "Give me an example of a time you saw one of these values in practice.",
      "When have you seen one of them not being met?",
      "Does the NHS still live up to its founding principles?",
    ],
    scaffold: [
      { step: "Name the values accurately", guidance: "Working together for patients; respect and dignity; commitment to quality of care; compassion; improving lives; everyone counts." },
      { step: "Mention founding principles briefly", guidance: "Comprehensive, available to all, free at the point of use, based on clinical need." },
      { step: "Choose one", guidance: "Pick one and justify it with an example." },
      { step: "Show nuance", guidance: "Values conflict under pressure; they depend on each other." },
    ],
    exemplar:
      "The NHS Constitution sets out six values: working together for patients; respect and dignity; commitment to quality of care; compassion; improving lives; and everyone counts. They sit alongside founding principles like care being available to all and based on clinical need, not the ability to pay.\n\nI think 'everyone counts' is the most important, because it's the one most at risk. On paper everyone has equal access, but the Marmot reviews show that people in the most deprived areas live shorter lives and spend more years in poor health. 'Everyone counts' means actively making sure services reach people who find it hardest to access them — not just treating whoever turns up.\n\nI saw a small example of this at the food bank where I volunteer: a nurse from the local practice ran a monthly blood pressure check there, because many visitors weren't registered with a GP. It was a simple idea, but it reached people the system usually misses.\n\nThat said, the values depend on each other — you can't treat someone with dignity without compassion, or improve lives without working together — so I'd see 'everyone counts' as the one that keeps the others honest.",
    annotations: [
      { excerpt: "sets out six values", note: "Accurate recall of all six values — a quick credibility win." },
      { excerpt: "the one most at risk", note: "Original, defensible reason for the choice." },
      { excerpt: "ran a monthly blood pressure check there", note: "Concrete example of the value in action." },
    ],
    keyPoints: [
      "Accurate list of the six values.",
      "Founding principles briefly.",
      "A justified choice with an example.",
      "Recognition that values interrelate and can be under pressure.",
    ],
    pitfalls: [
      "Inventing values or confusing them with the '6 Cs' of nursing.",
      "Listing without choosing.",
      "No example.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["nhs-constitution", "marmot-review"],
    tags: ["nhs-values", "nhs-constitution", "inequality"],
  },
  {
    slug: "biggest-challenge-facing-nhs",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel", "online"],
    difficulty: 3,
    question: "What do you think is the biggest challenge facing the NHS at the moment?",
    whatIsBeingTested: "Awareness of current issues, ability to prioritise and explain causes, and balanced thinking about solutions.",
    followUps: [
      "What would you do about it if you were in charge?",
      "How does this challenge affect doctors day to day?",
      "Is the NHS model sustainable?",
    ],
    scaffold: [
      { step: "Pick one main challenge", guidance: "E.g. demand from an ageing population with multiple conditions; workforce; social care and delayed discharge; waiting lists; inequalities." },
      { step: "Explain the causes", guidance: "Why it's happening — show understanding of connections." },
      { step: "Show the impact", guidance: "On patients and staff." },
      { step: "Discuss responses", guidance: "Current approaches (e.g. 10 Year Health Plan shifts, integrated care) and their feasibility." },
      { step: "Acknowledge interconnections", guidance: "Challenges link together." },
    ],
    exemplar:
      "I think the biggest underlying challenge is rising demand from people living longer with several long-term conditions, in a system designed around treating single illnesses episodically in hospital.\n\nPeople are living longer, which is a success, but many live with conditions like diabetes, heart failure and dementia together. They need coordinated, continuing care — yet much of the NHS is organised in separate specialties and separate organisations, and social care is funded and run separately by councils.\n\nYou can see the effect across the system. When social care can't support someone at home, patients who are medically fit stay in hospital; that means beds aren't available for patients waiting in A&E; which contributes to long waits and pressure on staff. Workforce shortages and waiting lists are real problems, but I think a lot of them are symptoms of this mismatch.\n\nThe government's 10 Year Health Plan tries to address it with a shift from hospital to community — neighbourhood teams bringing GPs, nurses, pharmacists and social care together — and a shift towards prevention. I think that's the right direction, but it depends on having the staff and funding in the community before hospital capacity is reduced, and on social care reform, which has been promised many times.\n\nFor doctors, I think it means increasingly working as generalists in teams across organisations — which is something I'd want to be good at.",
    annotations: [
      { excerpt: "a system designed around treating single illnesses episodically", note: "Identifies a structural cause, not just a symptom." },
      { excerpt: "When social care can't support someone at home", note: "Traces the chain of cause and effect clearly." },
      { excerpt: "it depends on having the staff and funding", note: "Balanced appraisal of the current policy response." },
    ],
    keyPoints: [
      "One clearly chosen challenge.",
      "Causal explanation and connections.",
      "Impact on patients and staff.",
      "Awareness of current responses and their limits.",
    ],
    pitfalls: [
      "Listing every problem without depth.",
      "Blaming a political party.",
      "Unsourced or inaccurate statistics.",
      "Proposing simplistic solutions ('just give it more money').",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["ten-year-health-plan", "nhs-structure-england", "marmot-review"],
    tags: ["nhs-challenges", "ageing", "social-care", "current-affairs"],
  },
  {
    slug: "should-doctors-strike",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel"],
    difficulty: 4,
    question: "Resident doctors in England have taken strike action over pay and training posts. Is it ever right for doctors to strike?",
    whatIsBeingTested: "Balanced reasoning about a contested, politically sensitive issue, weighing duties to patients against workers' rights and system consequences.",
    followUps: [
      "Would you strike as a resident doctor?",
      "How can patient safety be protected during strikes?",
      "What are the long-term risks of not resolving the dispute?",
    ],
    scaffold: [
      { step: "Context (neutral)", guidance: "Resident doctors (formerly 'junior doctors') in England have taken repeated industrial action in recent years; the BMA cites pay erosion and a shortage of specialty training posts; the government points to recent pay rises and plans for more training posts. Avoid party politics." },
      { step: "For", guidance: "Legal right; last resort; recruitment and retention affect future patient safety; morale." },
      { step: "Against", guidance: "Cancelled appointments and procedures cause harm and distress; strain on colleagues; trust in the profession." },
      { step: "Conditions", guidance: "Emergency care maintained; advance notice; proportionate; last resort after negotiation." },
      { step: "Conclude", guidance: "Reasoned view acknowledging harms, and respect for colleagues who choose differently." },
    ],
    exemplar:
      "Resident doctors in England have taken strike action several times in recent years. The BMA argues that pay has fallen in real terms over the long term and that there aren't enough specialty training posts for the doctors finishing their foundation years. The government's position is that pay has risen substantially recently and that it's increasing training posts. I'll try to focus on the principle rather than the specific offer.\n\nThe argument for doctors being able to strike is that they're employees with the same legal rights as others, and sometimes industrial action is the only way to change conditions. If doctors leave for other countries or other careers, that ultimately harms patients too.\n\nThe argument against is that strikes directly affect patients — thousands of appointments and operations get postponed, which causes distress and in some cases real harm, and puts pressure on colleagues. There's also a risk to public trust.\n\nI think the key is how it's done. Strikes where emergency and urgent care are protected, with plenty of notice so hospitals can re-plan care, reduce the risk considerably. It should also be a last resort after negotiation has genuinely failed.\n\nSo my view is that strike action can be justified, but only with strong patient safeguards, and doctors should be honest about its costs rather than claiming it causes no harm. I'd also respect colleagues who decide not to strike — it's an individual conscience decision.",
    annotations: [
      { excerpt: "I'll try to focus on the principle", note: "Signals neutrality on a politically charged topic — wise." },
      { excerpt: "that ultimately harms patients too", note: "The patient-safety argument for striking — the strongest version of the 'for' case." },
      { excerpt: "I think the key is how it's done", note: "Moves from binary to conditions — mature weighing." },
    ],
    keyPoints: [
      "Neutral, accurate context of both sides' positions.",
      "Patient-centred arguments on both sides.",
      "Conditions that reduce harm.",
      "A reasoned conclusion that respects colleagues' choices.",
    ],
    pitfalls: [
      "Political point-scoring.",
      "Precise pay figures stated as fact without a source.",
      "Ignoring harm to patients.",
      "Condemning striking doctors as uncaring.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["gmc-good-medical-practice", "nhs-structure-england"],
    tags: ["industrial-action", "workforce", "current-affairs"],
  },
  {
    slug: "health-inequalities",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel", "online"],
    difficulty: 3,
    question: "What are health inequalities, and what can doctors do about them?",
    whatIsBeingTested: "Understanding of the social determinants of health and realistic ideas for action at individual, practice and system level.",
    followUps: [
      "Aren't health inequalities a problem for politicians, not doctors?",
      "Give an example of a health inequality in the UK.",
      "What is proportionate universalism?",
    ],
    scaffold: [
      { step: "Define", guidance: "Avoidable, unfair differences in health between groups — by deprivation, ethnicity, geography, disability, etc." },
      { step: "Evidence and causes", guidance: "Social gradient (Marmot); social determinants: income, housing, education, work, environment; access and trust in services." },
      { step: "What doctors can do", guidance: "Individual: ask about social circumstances, adapt communication, avoid bias. Practice: outreach, flexible access, social prescribing, interpreters. System: advocacy, research, data." },
      { step: "Limits and nuance", guidance: "Most causes lie outside healthcare; doctors can't fix them alone but can influence." },
    ],
    exemplar:
      "Health inequalities are avoidable, unfair differences in health between groups of people — for example, people in the most deprived areas of England live considerably shorter lives, and spend many more years in poor health, than people in the least deprived areas.\n\nThe Marmot reviews showed this isn't just a gap between the richest and poorest: health follows a gradient all the way down the social ladder. Most of the causes lie outside the NHS — income, housing, education, work and the environment people live in. But healthcare can widen or narrow the gap, depending on who finds it easy to access.\n\nDoctors can act at several levels. In the consultation, they can ask about social circumstances, use interpreters, adapt how they explain things, and be aware of their own biases. At practice level, they can make services easier to reach — outreach clinics, flexible appointments, social prescribing to link people with support for things like debt or isolation. And at a system level, doctors have a strong voice: they can collect data, do research and advocate for policies such as better housing or smoke-free legislation.\n\nDoctors can't solve inequality on their own, and it would be naïve to suggest otherwise. But I think recognising it — and the idea of proportionate universalism, providing care for everyone but with more support where need is greater — changes how you practise.",
    annotations: [
      { excerpt: "avoidable, unfair differences", note: "Precise definition — distinguishes inequalities from simple differences." },
      { excerpt: "health follows a gradient", note: "Uses Marmot's key concept correctly." },
      { excerpt: "Doctors can act at several levels", note: "Structured, practical answer across individual, practice and system levels." },
    ],
    keyPoints: [
      "Clear definition and an example.",
      "Social gradient and social determinants.",
      "Actions at individual, practice and system levels.",
      "Realism about doctors' limits.",
    ],
    pitfalls: [
      "Blaming individuals' 'lifestyle choices'.",
      "Vague answers ('treat everyone equally').",
      "Inaccurate statistics.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["marmot-review", "nhs-constitution", "ten-year-health-plan"],
    tags: ["inequality", "public-health", "social-determinants"],
  },
  {
    slug: "sugar-tax-obesity",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel"],
    difficulty: 3,
    question: "Should the government tax unhealthy food to tackle obesity?",
    whatIsBeingTested: "Public-health reasoning: individual liberty versus population benefit, evidence, and equity effects.",
    followUps: [
      "Isn't this the 'nanny state'?",
      "Is a tax on food regressive?",
      "What else could be done instead?",
    ],
    scaffold: [
      { step: "Context", guidance: "Obesity linked to type 2 diabetes, heart disease and some cancers; the UK soft drinks industry levy (2018) led manufacturers to cut sugar." },
      { step: "For", guidance: "Population-level effect; industry reformulation; revenue for health; addresses environmental drivers." },
      { step: "Against", guidance: "Liberty; regressive (hits poorer households harder); substitution; complex causes." },
      { step: "Evidence and design", guidance: "Design matters: tiered levies that drive reformulation; combine with subsidies, reformulation targets, advertising limits." },
      { step: "Conclude", guidance: "Supportive if designed to change products and paired with measures to protect low-income households." },
    ],
    exemplar:
      "Obesity is a major driver of type 2 diabetes, heart disease, joint problems and some cancers, and it's more common in deprived areas — so it's both a health problem and an inequality problem.\n\nThe UK already has an example: the soft drinks industry levy, introduced in 2018. It was tiered by sugar content, and the interesting thing is that its main effect came through manufacturers reformulating their drinks to avoid the tax, rather than people paying more. Sugar in soft drinks fell substantially, and some studies suggest a possible reduction in childhood obesity, though it's hard to prove cause and effect.\n\nThe arguments against taxing food more widely are real. Some people see it as the state interfering in personal choices. Food taxes can be regressive, because poorer households spend a larger share of their income on food. And people might just switch to other unhealthy products.\n\nI think the design matters more than the principle. A tax aimed at getting companies to change their products, like the drinks levy, avoids putting the burden on individuals. And it works best as part of a package — subsidising healthy food, restricting junk food advertising to children, and funding services — because environments shape choices more than willpower.\n\nSo I'd support well-designed taxes that drive reformulation, as long as the revenue helps the communities most affected.",
    annotations: [
      { excerpt: "its main effect came through manufacturers reformulating", note: "Accurate, sophisticated insight about how the levy worked." },
      { excerpt: "though it's hard to prove cause and effect", note: "Appropriate caution about the evidence." },
      { excerpt: "Food taxes can be regressive", note: "Engages seriously with the equity objection." },
    ],
    keyPoints: [
      "Health and inequality impact of obesity.",
      "Evidence from the soft drinks industry levy.",
      "Liberty and regressivity objections.",
      "Design and complementary measures.",
    ],
    pitfalls: [
      "Blaming individuals ('they should just eat less').",
      "Overstating evidence.",
      "Ignoring the impact on low-income families.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["marmot-review", "ten-year-health-plan"],
    tags: ["public-health", "obesity", "policy"],
  },
  {
    slug: "ai-in-healthcare",
    category: "nhs-current-affairs",
    formats: ["mmi", "panel", "online"],
    difficulty: 3,
    question: "Artificial intelligence is increasingly used in healthcare. Will AI replace doctors?",
    whatIsBeingTested: "Balanced, informed thinking about technology in medicine, including benefits, risks, ethics and what remains distinctively human in the doctor's role.",
    followUps: [
      "Who is responsible if an AI system makes an error?",
      "How could AI make health inequalities worse?",
      "How should doctors be trained to use AI?",
    ],
    scaffold: [
      { step: "Where AI helps now", guidance: "Image analysis (e.g. radiology, retinal scans), triage, documentation and administration, predicting deterioration." },
      { step: "Benefits", guidance: "Speed, consistency, freeing clinician time, access." },
      { step: "Risks", guidance: "Bias from training data, errors and over-reliance, accountability, privacy, explainability, digital exclusion." },
      { step: "What remains human", guidance: "Judgement under uncertainty, integrating context and values, communication, trust, accountability." },
      { step: "Conclude", guidance: "Changes rather than replaces the role; doctors need to use it critically." },
    ],
    exemplar:
      "I don't think AI will replace doctors, but I think it will change what doctors spend their time doing.\n\nIt's already useful in areas that involve recognising patterns in large amounts of data — reading scans, screening retinal images, flagging patients whose observations suggest they're deteriorating. Tools that write up clinical notes from a consultation could give doctors back time with patients, and the NHS's 10 Year Health Plan puts a lot of weight on this kind of digital shift.\n\nBut there are real risks. AI systems learn from existing data, so if that data under-represents certain groups — for example, skin conditions in darker skin — the system may perform worse for them and widen inequalities. There's the risk of over-reliance, where clinicians stop questioning outputs. And there are hard questions about accountability when something goes wrong, and about privacy.\n\nWhat I think stays human is the part of medicine that sits around the data: understanding what matters to a particular patient, weighing uncertain options with them, communicating bad news, taking responsibility for a decision. A system might tell you the probability of a diagnosis; it doesn't sit with the family deciding what to do.\n\nSo I'd see AI as a powerful tool that doctors will need to understand well enough to use critically — knowing its limits, checking it against the patient in front of them, and speaking up when it's wrong.",
    annotations: [
      { excerpt: "change what doctors spend their time doing", note: "A clear thesis in the first sentence." },
      { excerpt: "skin conditions in darker skin", note: "Specific, well-known example of algorithmic bias." },
      { excerpt: "doesn't sit with the family deciding what to do", note: "Articulates the human element concretely." },
    ],
    keyPoints: [
      "Concrete current applications.",
      "Benefits and risks (bias, over-reliance, accountability, privacy).",
      "What remains distinctively human.",
      "Doctors as critical users of AI.",
    ],
    pitfalls: [
      "Techno-utopian or dismissive extremes.",
      "Vague claims with no examples.",
      "Ignoring equity and accountability.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["ten-year-health-plan"],
    tags: ["technology", "ai", "future-of-medicine"],
  },
  {
    slug: "physician-assistants-role",
    category: "nhs-current-affairs",
    formats: ["panel", "mmi"],
    difficulty: 4,
    question: "There has been a lot of debate about the role of physician associates in the NHS. What do you understand about this, and what is your view?",
    whatIsBeingTested: "Awareness of a live workforce debate, accuracy, and respect for colleagues while reasoning about patient safety and role clarity.",
    followUps: [
      "Why were doctors concerned?",
      "How can patients be sure who is treating them?",
      "What is the value of having different roles in a team?",
    ],
    scaffold: [
      { step: "Background", guidance: "PAs introduced to support medical teams; rapid expansion; concerns about role confusion, scope, supervision and impact on doctors' training." },
      { step: "Leng review (2025)", guidance: "No convincing evidence to abolish; rename to 'physician assistant'; no undifferentiated patients except within national protocols; named supervising doctor; secondary care first; government accepted." },
      { step: "Both perspectives", guidance: "Value of additional capacity and continuity versus patient safety and clarity." },
      { step: "Conclude", guidance: "Clear roles and supervision protect patients and colleagues alike; respect for PAs as team members." },
    ],
    exemplar:
      "Physician associates were introduced to support doctors — taking histories, examining patients and helping with investigations — under a doctor's supervision. The number grew quickly, and concerns emerged, particularly from doctors and some patients' families, about whether patients understood they weren't being seen by a doctor, how well PAs were supervised, whether they were seeing patients with undiagnosed problems, and whether they were taking training opportunities from resident doctors.\n\nIn late 2024 the government commissioned an independent review, led by Professor Gillian Leng, which reported in July 2025. It didn't find convincing evidence to scrap the role, but recommended renaming them 'physician assistants' to make clear they're not doctors, that they shouldn't see undifferentiated patients except within defined national protocols, and that each should have a named supervising doctor. The government accepted the recommendations.\n\nMy view is that the debate was really about clarity and safety rather than the individuals in these roles. Having more people in the team can help — PAs often provide continuity on a ward where doctors rotate. But patients have a right to know who's treating them, and diagnosing an undifferentiated problem is the core of a doctor's long training. Clear boundaries and supervision protect patients and PAs themselves.\n\nI'd also want to make sure the debate never became disrespectful to colleagues who are doing the job they were employed to do.",
    annotations: [
      { excerpt: "under a doctor's supervision", note: "Accurate framing from the start." },
      { excerpt: "It didn't find convincing evidence to scrap the role", note: "Accurate account of the review's conclusions." },
      { excerpt: "never became disrespectful to colleagues", note: "Professionalism — interviewers watch closely for this." },
    ],
    keyPoints: [
      "Accurate background and concerns.",
      "Leng review recommendations.",
      "Balanced consideration.",
      "Respect for colleagues.",
    ],
    pitfalls: [
      "Disparaging PAs.",
      "Outdated or inaccurate facts.",
      "No view at all.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["leng-review", "gmc-good-medical-practice"],
    tags: ["workforce", "mdt", "patient-safety", "current-affairs"],
  },
];
