import type { Question } from "../schema";

export const personalQualitiesQuestions: Question[] = [
  {
    slug: "teamwork-example",
    category: "personal-qualities",
    formats: ["mmi", "panel", "online"],
    difficulty: 2,
    question: "Tell me about a time you worked in a team that faced a problem. What was your role, and what did you learn?",
    whatIsBeingTested: "Teamwork skills demonstrated through your own actions, plus reflection on what makes teams work — essential in multidisciplinary healthcare.",
    followUps: [
      "What would you do differently?",
      "What makes a good team member as opposed to a good leader?",
      "How is teamwork in medicine different from teamwork at school?",
    ],
    scaffold: [
      { step: "Situation and task", guidance: "Brief context and the specific problem. Make your role clear." },
      { step: "Action", guidance: "What YOU did — first person — and why. This is most of the answer." },
      { step: "Result", guidance: "What happened, honestly." },
      { step: "Reflection", guidance: "What you learned about teams, and how it applies to healthcare teams." },
    ],
    exemplar:
      "Last year I was part of a Young Enterprise team of six, with three weeks to launch a product. Two members had stopped coming to meetings, and the rest of us were getting resentful.\n\nI was finance lead, so I needed their input on costs, but I was more worried the team would split. Rather than complaining to our teacher, I messaged each of them separately and asked how things were going. One was overwhelmed by coursework deadlines; the other felt her ideas had been dismissed in the first meeting. I suggested in our next meeting that we reallocate tasks by preference and add a ten-minute check-in each week where everyone could say what they were struggling with. I also made a point of building on her design idea, which we ended up using.\n\nBoth of them re-engaged, and we launched on time and made a small profit.\n\nWhat I learned is that disengagement usually has a reason worth asking about, and that assuming the worst about a colleague damages the team more than the original problem. In a hospital, where a team might include a nurse on a double shift or a junior doctor who's out of their depth, I think asking 'what's going on?' before judging matters even more — because patients bear the cost of a team that isn't talking.",
    annotations: [
      { excerpt: "I messaged each of them separately", note: "Clear, specific action by the candidate — the heart of a STAR answer." },
      { excerpt: "building on her design idea", note: "Shows inclusion in practice, not just in theory." },
      { excerpt: "disengagement usually has a reason worth asking about", note: "Genuine insight, well generalised to healthcare." },
      { excerpt: "we launched on time and made a small profit", note: "Concrete result. A sentence on what they'd do differently would complete the reflection." },
    ],
    keyPoints: [
      "Clear personal role and actions.",
      "Communication and inclusion as teamwork skills.",
      "An honest result.",
      "Reflection linked to multidisciplinary teams.",
    ],
    pitfalls: [
      "'We' throughout, so your contribution is invisible.",
      "Portraying yourself as the hero who fixed everyone.",
      "Blaming teammates.",
      "No reflection.",
    ],
    frameworks: [{ slug: "star", primary: true }],
    reading: ["gmc-good-medical-practice"],
    tags: ["teamwork", "star"],
  },
  {
    slug: "leadership-example",
    category: "personal-qualities",
    formats: ["mmi", "panel"],
    difficulty: 2,
    question: "Describe a time you showed leadership. Why is leadership important for doctors?",
    whatIsBeingTested: "Understanding that leadership is about enabling others, not being in charge — and awareness that all doctors lead, formally or informally.",
    followUps: [
      "Do you think leaders are born or made?",
      "Can you lead without a title?",
      "Tell me about a time you followed someone else's lead.",
    ],
    scaffold: [
      { step: "STAR example", guidance: "Choose an example where you enabled others, made a decision or took responsibility." },
      { step: "Your leadership style", guidance: "What you did to involve, motivate or support people." },
      { step: "Why leadership matters for doctors", guidance: "Leading ward rounds, handing over, teaching, raising concerns, improving services; leadership at every level." },
      { step: "Followership", guidance: "Good leaders also follow — respecting others' expertise." },
    ],
    exemplar:
      "As captain of my school's netball team, I noticed our younger players rarely spoke in team talks and seemed to lose confidence after mistakes. After a heavy defeat, rather than going over what went wrong, I asked each player to name one thing that went well and one thing they wanted to work on, and I paired the younger players with older ones for our warm-ups.\n\nOver the season, the younger players started contributing ideas, and one suggested a defensive change that won us two close matches. I learned that leadership is often less about giving instructions and more about creating a space where people feel able to speak up.\n\nI think that matters in medicine because every doctor leads — a foundation doctor coordinates care on a night shift, a registrar runs a resuscitation, a consultant sets the culture of a team. The Mid Staffordshire inquiry showed how dangerous it is when staff don't feel able to raise concerns, and much of that comes down to how leaders behave.\n\nBut I also think good leaders know when to follow. On a ward, a nurse or pharmacist may know far more about a specific issue, and the best leaders I saw on placement asked for their views before deciding.",
    annotations: [
      { excerpt: "rather than going over what went wrong", note: "A deliberate leadership choice, explained." },
      { excerpt: "creating a space where people feel able to speak up", note: "Links leadership to psychological safety — a sophisticated insight." },
      { excerpt: "every doctor leads", note: "Correctly frames leadership as distributed, not hierarchical." },
      { excerpt: "good leaders know when to follow", note: "Pre-empts a common follow-up and shows humility." },
    ],
    keyPoints: [
      "Leadership as enabling others.",
      "Specific actions and a result.",
      "Why all doctors lead, with examples.",
      "Value of followership and psychological safety.",
    ],
    pitfalls: [
      "Equating leadership with being in charge or telling people what to do.",
      "Listing titles (head girl, captain) with no actions.",
      "Ignoring the role of others.",
    ],
    frameworks: [{ slug: "star", primary: true }],
    reading: ["francis-report", "gmc-good-medical-practice"],
    tags: ["leadership", "star"],
  },
  {
    slug: "tell-me-about-a-mistake",
    category: "personal-qualities",
    formats: ["mmi", "panel", "online"],
    difficulty: 3,
    question: "Tell me about a mistake you have made. What did you do about it?",
    whatIsBeingTested: "Honesty, ownership, reflection and learning — the qualities behind the professional duty of candour.",
    followUps: [
      "How did you feel at the time?",
      "What would you do if you made a mistake that harmed a patient?",
      "Why is it so hard for people to admit mistakes?",
    ],
    scaffold: [
      { step: "Choose a real mistake", guidance: "Genuine but not catastrophic or unprofessional; one where you affected someone else is ideal." },
      { step: "Describe and own it", guidance: "Briefly, without excuses." },
      { step: "Feelings", guidance: "Honestly, including defensiveness if it was there." },
      { step: "What you did", guidance: "Told someone, apologised, put it right." },
      { step: "What you learned and changed", guidance: "Specific change, with evidence it has stuck. Link to medicine and candour." },
    ],
    exemplar:
      "Last spring I agreed to cover extra shifts at the café where I work in the same fortnight as a chemistry coursework deadline. I left the write-up too late and realised the night before that I wouldn't finish it properly.\n\nMy first instinct was to rush something and hope for the best, and I felt embarrassed and a bit defensive — I'd told myself I could handle both. But I emailed my teacher that evening, explained honestly that I'd over-committed, and asked for two more days. She agreed, though she pointed out that telling her earlier would have made it easier for her to plan.\n\nLooking back, the real mistake wasn't the late coursework but saying yes to everything without checking what I'd already committed to. I thought that made me reliable, but actually it risked letting people down.\n\nNow I plan my week each Sunday and check new commitments against it, and I've got better at saying 'not this week'. I haven't missed a deadline since.\n\nIn medicine I know mistakes will happen, and some will affect patients. What I took from this is that telling someone early — even when it's uncomfortable — gives everyone the best chance to fix things. That's essentially what the duty of candour asks of doctors.",
    annotations: [
      { excerpt: "I felt embarrassed and a bit defensive", note: "Honest emotion — shows self-awareness." },
      { excerpt: "the real mistake wasn't the late coursework", note: "Analysis goes beyond the event to the underlying cause." },
      { excerpt: "I haven't missed a deadline since", note: "Evidence the lesson changed behaviour." },
      { excerpt: "duty of candour", note: "Links personal learning to a professional principle, briefly and appropriately." },
    ],
    keyPoints: [
      "A genuine mistake, owned without excuses.",
      "Prompt honesty and action to put it right.",
      "Root-cause reflection.",
      "Evidence of changed behaviour.",
      "Link to openness and candour in medicine.",
    ],
    pitfalls: [
      "A disguised strength ('I cared too much').",
      "Blaming others or circumstances.",
      "A serious ethical lapse (cheating, dishonesty) that raises concerns.",
      "No evidence of change.",
    ],
    frameworks: [{ slug: "gibbs-reflective-cycle", primary: true }, { slug: "star" }],
    reading: ["bawa-garba-and-candour", "do-no-harm"],
    tags: ["mistakes", "candour", "reflection"],
  },
  {
    slug: "resilience-setback",
    category: "personal-qualities",
    formats: ["mmi", "panel", "online"],
    difficulty: 2,
    question: "Tell me about a time you faced a significant setback. How did you deal with it?",
    whatIsBeingTested: "Resilience understood as adaptive recovery and seeking support — not invulnerability.",
    followUps: [
      "Who do you turn to when things are difficult?",
      "What does resilience mean to you?",
      "How might the setbacks you face in medicine differ?",
    ],
    scaffold: [
      { step: "The setback", guidance: "Something genuinely difficult but that you can discuss comfortably." },
      { step: "Initial response", guidance: "Honest — including struggling." },
      { step: "What you did", guidance: "Practical steps, support sought, perspective gained." },
      { step: "Outcome and learning", guidance: "What resilience means to you now; how it will help in medicine." },
    ],
    exemplar:
      "In Year 12 I badly underperformed in my first set of chemistry mocks — I got a D when I'd been predicted an A. I'd always found science fairly natural, so it knocked my confidence and, for about a week, I seriously wondered whether medicine was realistic.\n\nAfter that week, I asked my teacher to go through the paper with me. It turned out I understood the content but was running out of time and losing marks on how I set out calculations. So I changed how I revised: timed past papers every weekend, and I started a small study group where we marked each other's answers against the mark schemes.\n\nBy the summer exams I got an A. But the bigger lesson was about how I respond to failure. I'd assumed resilience meant not being affected, but I was affected — what helped was asking for help quickly, finding out specifically what had gone wrong, and making a plan.\n\nIn medicine, the setbacks will be bigger — a patient deteriorating, a failed exam, a difficult rotation — and I expect to feel them. But I now trust that process: talk to someone, understand what happened, and change something.",
    annotations: [
      { excerpt: "I seriously wondered whether medicine was realistic", note: "Honest about the emotional impact — more credible than claiming to be unshakeable." },
      { excerpt: "asked my teacher to go through the paper", note: "Seeking feedback: a key resilience behaviour." },
      { excerpt: "I'd assumed resilience meant not being affected", note: "A mature redefinition of resilience." },
    ],
    keyPoints: [
      "A real setback and honest reaction.",
      "Active coping: support, analysis, plan.",
      "Resilience as recovery, not invulnerability.",
      "Transferable process for medicine.",
    ],
    pitfalls: [
      "A trivial setback or one that reveals poor judgement.",
      "Claiming nothing affects you.",
      "A setback that is still very raw and hard to discuss in interview.",
    ],
    frameworks: [{ slug: "star", primary: true }, { slug: "gibbs-reflective-cycle" }],
    reading: ["this-is-going-to-hurt"],
    tags: ["resilience", "setback"],
  },
  {
    slug: "empathy-vs-sympathy",
    category: "personal-qualities",
    formats: ["mmi", "panel"],
    difficulty: 2,
    question: "What is the difference between empathy and sympathy? Give an example of when you showed empathy.",
    whatIsBeingTested: "Conceptual clarity about empathy and the ability to demonstrate it in practice.",
    followUps: [
      "Can a doctor be too empathetic?",
      "Can empathy be taught?",
      "How do you show empathy when you're very busy?",
    ],
    scaffold: [
      { step: "Define clearly", guidance: "Sympathy: feeling sorry for someone, from the outside. Empathy: trying to understand how they feel from their perspective and communicating that understanding." },
      { step: "Example", guidance: "A specific moment when you tried to understand someone's perspective and it changed your response." },
      { step: "Why it matters in medicine", guidance: "Trust, disclosure, adherence, patient experience." },
      { step: "Nuance", guidance: "Balance with professional boundaries and avoiding burnout." },
    ],
    exemplar:
      "Sympathy is feeling sorry for someone — it's looking at their situation from the outside. Empathy is trying to understand how things feel from their side, and showing them you've understood. Sympathy might say 'That's awful'; empathy might say 'It sounds like you're worried about how you'll manage at home.'\n\nAt the care home where I volunteer, a resident refused to come to activities and was often described as 'difficult'. I started chatting to him in his room and found out he'd been a keen musician and was embarrassed that his hands now shook too much to play. The group activities often involved music, which reminded him of what he'd lost. I mentioned this to the activities coordinator, and they started asking him to choose the records instead. He began joining in.\n\nIn medicine, I think empathy matters because patients who feel understood tell you more, trust your advice more and cope better. But I also think doctors need boundaries — you can understand someone's distress without taking it all home — otherwise you risk burnout and your judgement suffers.",
    annotations: [
      { excerpt: "Sympathy might say 'That's awful'; empathy might say", note: "Concrete contrast makes the distinction vivid." },
      { excerpt: "embarrassed that his hands now shook", note: "Empathy shown through curiosity about his perspective, leading to action." },
      { excerpt: "you can understand someone's distress without taking it all home", note: "Nuance about boundaries — anticipates a common follow-up." },
    ],
    keyPoints: [
      "Accurate distinction between empathy and sympathy.",
      "A specific example where understanding changed action.",
      "Why empathy improves care.",
      "Boundaries and sustainability.",
    ],
    pitfalls: [
      "Circular or vague definitions.",
      "An example that shows sympathy, not empathy.",
      "Implying empathy means sharing all of a patient's emotions.",
    ],
    frameworks: [{ slug: "star" }, { slug: "ice" }],
    reading: ["when-breath-becomes-air", "being-mortal"],
    tags: ["empathy", "communication"],
  },
  {
    slug: "conflict-with-colleague",
    category: "personal-qualities",
    formats: ["mmi", "panel"],
    difficulty: 3,
    question: "Tell me about a time you disagreed with someone you were working with. How did you resolve it?",
    whatIsBeingTested: "Conflict resolution, respectful communication, openness to being wrong, and focus on shared goals.",
    followUps: [
      "What if you had been sure you were right?",
      "What would you do if you disagreed with a senior doctor's decision about a patient?",
      "When is it right to escalate a disagreement?",
    ],
    scaffold: [
      { step: "Situation", guidance: "The disagreement and why it mattered." },
      { step: "Understand their view", guidance: "How you listened and sought their reasoning." },
      { step: "Find common ground", guidance: "Shared goal; compromise or evidence." },
      { step: "Outcome and learning", guidance: "What happened, what you learned; link to clinical teams and escalation." },
    ],
    exemplar:
      "In my EPQ group — we'd each written a section of a shared report on antibiotic resistance — another student wanted to include a statistic from a news article I thought was unreliable. She felt strongly it made the introduction more powerful, and our first conversation got quite tense.\n\nI realised I'd started by telling her she was wrong rather than asking why she'd chosen it. So I suggested we look at the source together. It turned out the article was quoting a real report, but the figure had been rounded and applied to the wrong year. We agreed to use the original report and her framing, which kept the impact she wanted with accurate data.\n\nWhat I learned is that disagreement goes better when you focus on the shared goal — for us, a good, accurate report — rather than on who's right. It also taught me to lead with a question rather than a verdict.\n\nIn medicine, I know disagreements affect patients. If I disagreed with a senior about a patient's care, I'd raise it respectfully and ask about their reasoning — they may know something I don't. But if I still had a genuine concern about patient safety, I'd have a duty to escalate it through the appropriate route.",
    annotations: [
      { excerpt: "I'd started by telling her she was wrong", note: "Honesty about their own contribution to the conflict." },
      { excerpt: "look at the source together", note: "Evidence-based resolution — a scientific approach to disagreement." },
      { excerpt: "lead with a question rather than a verdict", note: "Concise, transferable lesson." },
      { excerpt: "I'd have a duty to escalate", note: "Correctly balances respect for seniors with patient safety." },
    ],
    keyPoints: [
      "Listening to understand the other view.",
      "Focus on the shared goal and evidence.",
      "Owning your part.",
      "Knowing when respectful challenge becomes escalation.",
    ],
    pitfalls: [
      "A story where you were simply right and the other person gave in.",
      "Avoiding conflict entirely ('I just let them have their way').",
      "Undermining seniors in the clinical follow-up.",
    ],
    frameworks: [{ slug: "star", primary: true }, { slug: "de-escalation" }],
    reading: ["gmc-good-medical-practice"],
    tags: ["conflict", "teamwork", "communication"],
  },
  {
    slug: "greatest-weakness",
    category: "personal-qualities",
    formats: ["panel", "mmi", "online"],
    difficulty: 2,
    question: "What is your greatest weakness?",
    whatIsBeingTested: "Honest self-awareness and a proactive approach to self-improvement — both essential to reflective practice.",
    followUps: [
      "How might that weakness affect you as a doctor?",
      "What feedback have others given you?",
      "What's a strength that could become a weakness in medicine?",
    ],
    scaffold: [
      { step: "Name a genuine weakness", guidance: "Real, relevant, not disqualifying (e.g. perfectionism that delays, difficulty delegating, public speaking nerves, taking on too much)." },
      { step: "Evidence", guidance: "A time it caused a problem." },
      { step: "What you're doing about it", guidance: "Concrete strategies." },
      { step: "Progress and relevance", guidance: "How far you've come and why it matters in medicine." },
    ],
    exemplar:
      "I find it hard to delegate. When I'm responsible for something, I tend to assume I'll do it better myself.\n\nThis became a problem when I organised a charity bake sale last year. I tried to handle the publicity, the rota and the finances myself, got overwhelmed the week before, and some of the rota was disorganised as a result. One of my friends said afterwards she'd have happily done the posters if I'd asked.\n\nSince then I've tried to be deliberate about it. When I led our school's science club this year, I gave each member ownership of one session rather than planning them all, and I've accepted that others will do things differently from me — often better.\n\nI think this matters in medicine because no doctor can do everything, and patient care depends on trusting colleagues and handing over properly. I'm still working on it — I notice the instinct to take over — but I'm much more aware of it than I was.",
    annotations: [
      { excerpt: "I find it hard to delegate", note: "A genuine weakness stated plainly — not a disguised strength." },
      { excerpt: "some of the rota was disorganised", note: "Shows the consequence honestly." },
      { excerpt: "I'm still working on it", note: "Honest about progress rather than claiming it's fixed." },
    ],
    keyPoints: [
      "A genuine, relevant weakness.",
      "Evidence of impact.",
      "Concrete strategies and progress.",
      "Relevance to medicine.",
    ],
    pitfalls: [
      "'I'm a perfectionist' or 'I work too hard' with no genuine downside.",
      "A weakness that undermines fitness to practise (e.g. dishonesty, not caring).",
      "No plan to improve.",
    ],
    frameworks: [{ slug: "gibbs-reflective-cycle" }, { slug: "star" }],
    reading: [],
    tags: ["self-awareness", "reflection"],
  },
];
