import type { Question } from "../schema";

export const scienceQuestions: Question[] = [
  {
    slug: "why-do-we-get-a-fever",
    category: "science-clinical-reasoning",
    formats: ["panel", "mmi", "oxbridge"],
    difficulty: 3,
    question: "Why do we get a temperature when we have an infection? Is it a good thing?",
    whatIsBeingTested: "Applying physiology (homeostasis, immune signalling) to a clinical phenomenon and evaluating it — not just describing it.",
    followUps: [
      "If fever is helpful, why do we give paracetamol?",
      "Why do you shiver when your temperature is rising?",
      "How is fever different from heatstroke?",
    ],
    scaffold: [
      { step: "Mechanism", guidance: "Immune cells release signalling molecules (pyrogens such as interleukins); these act on the hypothalamus via prostaglandins to raise the temperature 'set point'." },
      { step: "Consequences", guidance: "Body now feels 'too cold' relative to the new set point: shivering, vasoconstriction, feeling cold — until the new temperature is reached." },
      { step: "Benefits", guidance: "Many pathogens replicate less efficiently at higher temperatures; some immune responses work better." },
      { step: "Costs", guidance: "Higher metabolic demand, fluid loss, discomfort; risks for vulnerable patients (e.g. frail, heart disease, febrile seizures in young children)." },
      { step: "Evaluate", guidance: "Generally an adaptive response; treat for comfort or where risks outweigh benefits." },
      { step: "Contrast", guidance: "Heatstroke: set point unchanged, heat-loss mechanisms overwhelmed — a different problem." },
    ],
    exemplar:
      "A fever is a controlled rise in body temperature, which is different from simply overheating.\n\nWhen immune cells detect an infection, they release signalling molecules — cytokines such as interleukin-1 — that travel to the hypothalamus, the brain's thermostat. There they trigger prostaglandin production, which raises the temperature 'set point'. So the body now thinks it's too cold: you feel chilly, blood vessels in the skin constrict to reduce heat loss, and you shiver to generate heat, until your temperature matches the new set point. When the infection settles, the set point drops again, and you sweat and flush to lose heat.\n\nWhether it's a good thing is a balance. Many bacteria and viruses replicate less efficiently at higher temperatures, and some parts of the immune response work better, so fever is probably an adaptive response that has evolved because it helps. But it has costs: it increases metabolic rate and oxygen demand, causes fluid loss, and can be dangerous for some people, like frail older patients or those with heart disease.\n\nParacetamol works by reducing prostaglandin production, lowering the set point. We mainly use it to make people more comfortable, rather than because the fever itself is harmful in a healthy person.\n\nThat's different from heatstroke, where the set point is normal but the body can't lose heat fast enough — which is why antipyretics don't really help there, and physical cooling is needed.",
    annotations: [
      { excerpt: "a controlled rise in body temperature", note: "Sets up the key concept (a raised set point) immediately." },
      { excerpt: "So the body now thinks it's too cold", note: "Explains shivering logically from the mechanism — shows understanding rather than recall." },
      { excerpt: "probably an adaptive response", note: "Appropriately hedged evaluation, weighing benefits and costs." },
      { excerpt: "antipyretics don't really help there", note: "Excellent extension showing the concept can be applied to a contrast case." },
    ],
    keyPoints: [
      "Cytokines → hypothalamus → prostaglandins → raised set point.",
      "Heat-conserving and heat-generating responses explained.",
      "Benefits and costs weighed.",
      "Antipyretics lower the set point; mostly for comfort.",
      "Distinction from heatstroke.",
    ],
    pitfalls: [
      "Saying the infection itself 'heats you up'.",
      "Claiming fever is always harmful and must be treated.",
      "Describing without evaluating.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["physiology", "homeostasis", "immunology"],
  },
  {
    slug: "how-vaccines-work-herd-immunity",
    category: "science-clinical-reasoning",
    formats: ["mmi", "panel"],
    difficulty: 2,
    question: "How do vaccines work, and what is herd immunity?",
    whatIsBeingTested: "Clear explanation of immunological memory and population-level protection, pitched for a non-specialist.",
    followUps: [
      "Why do some vaccines need boosters and others don't?",
      "Why is the herd immunity threshold higher for measles than for other diseases?",
      "How would you explain this to a worried parent?",
    ],
    scaffold: [
      { step: "Immune memory", guidance: "Vaccine presents antigen (weakened, inactivated, protein subunit, or genetic instructions like mRNA) → adaptive immune response → memory B and T cells → faster, stronger response on real exposure." },
      { step: "Herd immunity", guidance: "When enough people are immune, transmission chains break, protecting those who can't be vaccinated or respond poorly." },
      { step: "Threshold", guidance: "Depends on how transmissible the disease is (basic reproduction number, R0); measles is highly contagious so needs about 95% coverage." },
      { step: "Limits", guidance: "Waning immunity, mutation (e.g. flu), vaccine effectiveness." },
    ],
    exemplar:
      "A vaccine trains the immune system to recognise a pathogen without the person having to get ill. It exposes the body to something that looks like the pathogen — a weakened or inactivated version, a protein from its surface, or genetic instructions, as in mRNA vaccines, that let our own cells make that protein briefly.\n\nThe immune system responds as if it were a real infection: B cells make antibodies, T cells are activated, and importantly, memory cells are formed. If the person later meets the real pathogen, those memory cells respond much faster and more strongly, often clearing it before it causes serious illness.\n\nHerd immunity is the idea that when a high enough proportion of the population is immune, the pathogen can't spread effectively, because each infected person is unlikely to meet someone susceptible. That protects people who can't be vaccinated — like newborn babies or people on chemotherapy.\n\nThe proportion needed depends on how contagious the disease is. Measles is extremely contagious — one person can infect many others — so around 95% of people need to be immune. For less contagious diseases the threshold is lower.\n\nSome vaccines need boosters because immunity wanes over time, and for things like flu, the virus changes each year, so the vaccine has to be updated.",
    annotations: [
      { excerpt: "without the person having to get ill", note: "Plain-language opener suitable for any audience." },
      { excerpt: "memory cells are formed", note: "Identifies the crucial mechanism behind long-term protection." },
      { excerpt: "each infected person is unlikely to meet someone susceptible", note: "Explains herd immunity mechanistically rather than just defining it." },
    ],
    keyPoints: [
      "Antigen exposure → adaptive response → memory cells.",
      "Types of vaccine briefly.",
      "Herd immunity mechanism and who it protects.",
      "Threshold depends on transmissibility (measles about 95%).",
      "Waning immunity and antigenic change.",
    ],
    pitfalls: [
      "Confusing antibodies with memory cells.",
      "Saying vaccines give you the disease.",
      "Overloading with jargon.",
    ],
    frameworks: [{ slug: "chunk-and-check", primary: true }],
    reading: [],
    tags: ["immunology", "vaccination", "public-health"],
  },
  {
    slug: "antibiotic-resistance",
    category: "science-clinical-reasoning",
    formats: ["mmi", "panel", "oxbridge"],
    difficulty: 3,
    question: "Why are bacteria becoming resistant to antibiotics, and what can be done about it?",
    whatIsBeingTested: "Applying natural selection to a clinical problem and understanding the behavioural and system-level responses.",
    followUps: [
      "Why don't we just develop new antibiotics?",
      "Why doesn't antibiotic resistance happen with viruses in the same way?",
      "What would you say to a patient demanding antibiotics for a cold?",
    ],
    scaffold: [
      { step: "Mechanism", guidance: "Random mutations; selection pressure from antibiotics kills susceptible bacteria; resistant ones survive and multiply; horizontal gene transfer (plasmids) spreads resistance." },
      { step: "Drivers", guidance: "Overprescribing (e.g. viral infections), incomplete courses debate, agricultural use, poor infection control, global travel." },
      { step: "Consequences", guidance: "Routine infections and surgery become riskier." },
      { step: "Solutions", guidance: "Stewardship, diagnostics, infection prevention, vaccination, agriculture regulation, incentives for new drug development." },
    ],
    exemplar:
      "Antibiotic resistance is evolution by natural selection happening fast enough for us to watch.\n\nIn any large population of bacteria, random mutations mean a few may happen to survive a particular antibiotic — perhaps they have an enzyme that breaks it down or a pump that removes it. When we use the antibiotic, it kills the susceptible bacteria and leaves the resistant ones with less competition, so they multiply. Bacteria can also share resistance genes directly with each other on plasmids, which means resistance can spread between different species.\n\nAnything that increases the use of antibiotics increases this selection pressure: prescribing them for viral infections where they don't help, using them heavily in farming, and poor infection control in hospitals allowing resistant bacteria to spread.\n\nIt matters because modern medicine depends on antibiotics — not just for infections but to make surgery, chemotherapy and caesarean sections safe.\n\nSolutions work at several levels: prescribers using antibiotics only when needed and choosing narrow-spectrum drugs — known as stewardship; better rapid tests so we know when they're needed; infection prevention like hand hygiene and vaccination, which reduces infections in the first place; and regulating agricultural use. New antibiotics are also needed, but they're commercially unattractive because we'd want to use them as little as possible, so governments are experimenting with different ways to pay for them.",
    annotations: [
      { excerpt: "evolution by natural selection happening fast enough", note: "Frames the answer with the core biological principle." },
      { excerpt: "share resistance genes directly with each other on plasmids", note: "Adds horizontal gene transfer — a mark of depth." },
      { excerpt: "commercially unattractive because we'd want to use them as little as possible", note: "Insightful point about the economics — good for follow-ups." },
    ],
    keyPoints: [
      "Mutation + selection pressure; horizontal gene transfer.",
      "Human, agricultural and hospital drivers.",
      "Why it threatens modern medicine.",
      "Multi-level solutions, including the economics of new drugs.",
    ],
    pitfalls: [
      "Saying the patient becomes resistant rather than the bacteria.",
      "Implying bacteria 'decide' to adapt.",
      "Only one solution.",
    ],
    frameworks: [{ slug: "thinking-aloud" }, { slug: "chunk-and-check" }],
    reading: [],
    tags: ["microbiology", "evolution", "public-health"],
  },
  {
    slug: "breathless-at-altitude",
    category: "science-clinical-reasoning",
    formats: ["oxbridge", "panel"],
    difficulty: 4,
    universities: ["oxford", "cambridge"],
    question: "Why do people become breathless when they climb a high mountain? How does the body adapt if they stay there?",
    whatIsBeingTested: "Applying gas exchange, partial pressures and homeostatic control to an unfamiliar scenario.",
    followUps: [
      "The percentage of oxygen in the air is the same at the top of Everest — so why is there less oxygen?",
      "Why would breathing faster make someone's blood less acidic, and why is that a problem?",
      "Why might athletes train at altitude?",
    ],
    scaffold: [
      { step: "Clarify the physics", guidance: "Oxygen fraction (~21%) is unchanged; total atmospheric pressure falls, so the partial pressure of oxygen falls." },
      { step: "Gas exchange", guidance: "Lower partial pressure gradient → less oxygen diffuses into blood → lower haemoglobin saturation → hypoxaemia." },
      { step: "Immediate response", guidance: "Peripheral chemoreceptors detect low oxygen → increased ventilation and heart rate → feeling breathless." },
      { step: "Consequence", guidance: "Hyperventilation blows off CO2 → respiratory alkalosis, which limits the drive to breathe." },
      { step: "Acclimatisation", guidance: "Kidneys excrete bicarbonate; erythropoietin → more red blood cells over weeks; other changes at cellular level." },
    ],
    exemplar:
      "The first thing I'd clarify is that the air at the top of a mountain still contains about 21% oxygen. The difference is that atmospheric pressure is much lower, so the partial pressure of oxygen — effectively how hard oxygen is being 'pushed' into the lungs — is lower.\n\nThat matters because oxygen moves from the alveoli into the blood by diffusion, down a partial pressure gradient. With a smaller gradient, less oxygen enters the blood, haemoglobin is less saturated, and tissues receive less oxygen.\n\nThe body detects this through chemoreceptors — I think mainly the ones in the carotid arteries — which sense low oxygen and increase the rate and depth of breathing. The heart rate also rises. That's why people feel breathless: their body is trying to compensate.\n\nBut breathing faster also blows off more carbon dioxide, which makes the blood more alkaline. Since CO2 is normally a strong stimulus to breathe, losing it limits how much further breathing can increase — so there's a tension between the two.\n\nIf someone stays at altitude, over days the kidneys excrete more bicarbonate to correct the alkalosis, allowing breathing to increase further. Over weeks, the kidneys release more erythropoietin, which stimulates red blood cell production, so the blood can carry more oxygen. I believe there are also changes in how readily haemoglobin releases oxygen to the tissues.\n\nThat's why athletes train at altitude — to increase their red cell mass — though I'd guess the benefit depends on how long they stay and on the individual.",
    annotations: [
      { excerpt: "still contains about 21% oxygen", note: "Anticipates and corrects the common misconception — often the interviewer's first probe." },
      { excerpt: "I think mainly the ones in the carotid arteries", note: "Flags uncertainty honestly while reasoning — exactly the Oxbridge style." },
      { excerpt: "there's a tension between the two", note: "Recognises competing control signals — higher-level thinking." },
      { excerpt: "I'd guess the benefit depends", note: "Tentative extension — fine, but an interviewer may push you to reason it out further." },
    ],
    keyPoints: [
      "Partial pressure, not percentage, falls.",
      "Reduced diffusion gradient → hypoxaemia.",
      "Chemoreceptors drive increased ventilation and heart rate.",
      "Respiratory alkalosis limits the response.",
      "Renal compensation and erythropoietin in acclimatisation.",
    ],
    pitfalls: [
      "Saying there is 'less oxygen in the air' without explaining.",
      "Stopping at 'breathe faster' without the CO2 consequence.",
      "Silence instead of reasoning when unsure.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["physiology", "respiration", "homeostasis", "oxbridge"],
  },
  {
    slug: "why-are-cells-small",
    category: "science-clinical-reasoning",
    formats: ["oxbridge"],
    difficulty: 3,
    universities: ["oxford", "cambridge"],
    question: "Why are most cells so small? Can you think of any exceptions, and how do they cope?",
    whatIsBeingTested: "Reasoning from a physical principle (surface area to volume, diffusion) and testing it against exceptions.",
    followUps: [
      "If a cell doubles in width, what happens to its surface area and volume?",
      "How does a neuron over a metre long survive?",
      "Why don't large animals just have larger cells?",
    ],
    scaffold: [
      { step: "Clarify", guidance: "What limits cell size? Think about what a cell needs to exchange with its surroundings." },
      { step: "Principle", guidance: "Surface area scales with length², volume with length³; as a cell grows, SA:V falls. Diffusion time increases with the square of distance." },
      { step: "Reason", guidance: "Metabolic needs scale with volume, supply with surface area; beyond a point, exchange can't keep up. Also a single nucleus controlling a large volume." },
      { step: "Check with exceptions", guidance: "Neurons (long but thin; axonal transport); eggs (mostly stored food, low metabolic rate); skeletal muscle fibres (multinucleate); some algae." },
      { step: "Conclude", guidance: "Size is limited by exchange and control; exceptions reveal adaptations that work around it." },
    ],
    exemplar:
      "I'd start by thinking about what a cell needs to do: take in oxygen and nutrients and get rid of waste, all across its membrane.\n\nIf I imagine a cube-shaped cell and double its side length, its surface area goes up four times but its volume goes up eight times. So as a cell gets bigger, it has proportionally less surface to supply more contents. The amount of metabolism depends roughly on volume, but exchange depends on surface area, so at some size the membrane can't keep up.\n\nThere's also a distance problem. Diffusion is fast over short distances but becomes very slow over longer ones — I think the time taken increases with the square of the distance — so molecules would take too long to reach the centre of a large cell. And one nucleus has to control everything in the cell, which gets harder in a larger volume.\n\nTesting that against exceptions: neurons can be over a metre long, but they're extremely thin, so no part of the cell is far from the membrane, and they use active transport along microtubules rather than relying on diffusion. Egg cells are huge, but most of their volume is stored food and they're not very metabolically active until fertilised. Skeletal muscle fibres are long, but they have many nuclei along their length.\n\nSo I'd conclude that cell size is limited by exchange and by control, and the exceptions are cells that have found ways around those limits — by changing shape, reducing metabolic demand, or having more nuclei.",
    annotations: [
      { excerpt: "If I imagine a cube-shaped cell and double its side length", note: "Uses a quick worked example — concrete and checkable." },
      { excerpt: "I think the time taken increases with the square of the distance", note: "States a relationship with appropriate hedging." },
      { excerpt: "Testing that against exceptions", note: "Actively tests the hypothesis — precisely what tutors want." },
    ],
    keyPoints: [
      "SA:V scaling explained quantitatively.",
      "Diffusion distance limitation.",
      "Nuclear control of volume.",
      "Exceptions with adaptations: neurons, eggs, muscle fibres.",
    ],
    pitfalls: [
      "Asserting 'surface area to volume ratio' without explaining why it matters.",
      "Ignoring the exceptions prompt.",
      "Giving up when unsure of an exact relationship.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["cell-biology", "diffusion", "scaling", "oxbridge"],
  },
  {
    slug: "estimate-heartbeats-lifetime",
    category: "science-clinical-reasoning",
    formats: ["oxbridge", "panel"],
    difficulty: 2,
    universities: ["oxford", "cambridge"],
    question: "Roughly how many times will your heart beat in your lifetime?",
    whatIsBeingTested: "Estimation, comfort with numbers, stating assumptions and sanity-checking — without a calculator.",
    followUps: [
      "Which of your assumptions has the biggest effect on the answer?",
      "How would the answer differ for a mouse, and why?",
      "How much blood does the heart pump in a lifetime?",
    ],
    scaffold: [
      { step: "Clarify", guidance: "An average person; an order-of-magnitude estimate is fine." },
      { step: "Assume", guidance: "Average heart rate ~70 bpm; lifespan ~80 years." },
      { step: "Calculate aloud", guidance: "Per hour → per day → per year → lifetime; round as you go." },
      { step: "Check", guidance: "Higher in childhood and exercise, lower in sleep — do these roughly cancel? Is the order of magnitude sensible?" },
      { step: "Extend", guidance: "Identify the most sensitive assumption; consider other species." },
    ],
    exemplar:
      "I'll aim for an order-of-magnitude estimate.\n\nI'll assume an average heart rate of around 70 beats per minute and a lifespan of about 80 years.\n\n70 beats a minute times 60 minutes is 4,200 beats an hour. Times 24 hours is roughly 100,000 beats a day — 4,200 times 24 is about 101,000, so 100,000 is a nice round number. Times 365 days is about 36 or 37 million beats a year. Times 80 years is roughly 3 billion.\n\nTo check it: my heart rate is higher as a baby — well over 100 — and during exercise, but lower during sleep, perhaps 50 or 60. Those probably partly cancel out, and even if my average is off by 10 or 20%, the answer is still 'a few billion'.\n\nThe assumption with the biggest effect is probably lifespan, although heart rate and lifespan both scale the answer proportionally.\n\nFor a mouse, the heart rate is much faster — hundreds of beats a minute — but the lifespan is only two or three years. I've read that many mammals end up with a similar number of heartbeats in a lifetime, around a billion, which is a curious pattern — humans seem to be an outlier on the high side.",
    annotations: [
      { excerpt: "I'll assume an average heart rate of around 70", note: "Assumptions stated explicitly before calculating." },
      { excerpt: "so 100,000 is a nice round number", note: "Sensible rounding aloud — keeps arithmetic manageable." },
      { excerpt: "Those probably partly cancel out", note: "Sanity check using physiological knowledge." },
      { excerpt: "I've read that many mammals", note: "Nice extension. If you mention a claim like this, be ready to discuss why it might be true (metabolic rate scaling)." },
    ],
    keyPoints: [
      "Clear assumptions.",
      "Stepwise arithmetic with sensible rounding.",
      "Sanity check and uncertainty.",
      "Answer ~3 billion (order of magnitude).",
    ],
    pitfalls: [
      "Silent calculation.",
      "False precision.",
      "Panicking over the arithmetic.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["estimation", "numeracy", "oxbridge"],
  },
  {
    slug: "elephants-and-cancer",
    category: "science-clinical-reasoning",
    formats: ["oxbridge"],
    difficulty: 5,
    universities: ["oxford", "cambridge"],
    question: "Elephants have far more cells than humans, yet they don't seem to get cancer more often. Why might that be surprising, and how might you explain it?",
    whatIsBeingTested: "Reasoning about probability, mutation and evolution from first principles, generating and testing hypotheses — a classic tutorial-style problem (Peto's paradox).",
    followUps: [
      "How would you test your hypothesis?",
      "Could studying elephants help treat human cancer?",
      "Why might natural selection favour cancer resistance in large, long-lived animals?",
    ],
    scaffold: [
      { step: "Why it's surprising", guidance: "Cancer arises from mutations during cell division; more cells and longer life → more divisions → more chances of cancer-causing mutations." },
      { step: "Generate hypotheses", guidance: "Better DNA repair; more tumour-suppressor genes; more readily triggered cell death (apoptosis); slower metabolism; tumours that are themselves attacked." },
      { step: "Evolutionary reasoning", guidance: "Large, long-lived animals would be under strong selection for cancer suppression, otherwise they'd die before reproducing." },
      { step: "Evidence (if known)", guidance: "Elephants have many extra copies of the tumour suppressor gene TP53, which may make damaged cells more likely to die." },
      { step: "Test", guidance: "Compare cancer rates across species; study cell responses to DNA damage in the lab." },
    ],
    exemplar:
      "It's surprising because cancer is thought to arise when cells accumulate mutations, and mutations happen mainly when DNA is copied during cell division. An elephant has many more cells than a human and lives a long time, so you'd expect vastly more cell divisions, and therefore many more chances for a cell to become cancerous. If every cell had the same risk, elephants should get cancer far more often than we do.\n\nSince they don't, something must be different. A few possibilities: their cells might repair DNA damage more effectively; they might be quicker to kill off damaged cells through apoptosis; they might have extra tumour-suppressor genes; or their cells might divide more slowly.\n\nFrom an evolutionary point of view, it makes sense that they'd have some protection. A large animal that takes years to reach reproductive age would be under strong pressure not to die of cancer first — so any mutation that reduced cancer risk would be strongly selected for.\n\nI've read that elephants actually have many copies of the gene TP53, which codes for p53, a protein that stops damaged cells dividing or triggers their death. So one idea is that their cells are more likely to die when their DNA is damaged, instead of carrying on and potentially becoming cancerous.\n\nTo test that, you could compare how elephant and human cells respond to DNA-damaging radiation in the lab — if elephant cells undergo apoptosis more readily, that would support it. And if we understood the mechanism, it might suggest ways of boosting similar pathways in humans, though I imagine that's very hard to do safely.",
    annotations: [
      { excerpt: "If every cell had the same risk", note: "States the underlying assumption explicitly — making the paradox precise." },
      { excerpt: "A few possibilities", note: "Generates several hypotheses before settling — excellent tutorial behaviour." },
      { excerpt: "From an evolutionary point of view", note: "Brings in a second level of explanation (why, not just how)." },
      { excerpt: "To test that", note: "Proposes a concrete experiment — the part many candidates skip." },
    ],
    keyPoints: [
      "Mutation-per-division logic made explicit.",
      "Multiple hypotheses.",
      "Evolutionary explanation.",
      "Known evidence (extra TP53 copies) if you have it — not required.",
      "Experimental test.",
    ],
    pitfalls: [
      "Just saying 'they have better genes'.",
      "Not explaining why it's surprising.",
      "Stating facts you're unsure of as certain.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["cancer", "evolution", "genetics", "oxbridge"],
  },
  {
    slug: "coffee-and-cancer-study",
    category: "science-clinical-reasoning",
    formats: ["oxbridge", "panel", "mmi"],
    difficulty: 4,
    question: "A newspaper headline says 'Coffee drinkers more likely to get lung cancer'. What questions would you ask about the research behind it, and how would you design a study to find out the truth?",
    whatIsBeingTested: "Critical appraisal: correlation versus causation, confounding, bias and study design.",
    followUps: [
      "Why can't we just do a randomised trial?",
      "What is a confounding variable?",
      "How should doctors communicate uncertain research to patients?",
    ],
    scaffold: [
      { step: "Questions about the study", guidance: "What type of study? How many people? How were coffee and cancer measured? Absolute or relative risk? Peer-reviewed?" },
      { step: "Confounding", guidance: "Smoking: people who drink more coffee may be more likely to smoke, and smoking causes lung cancer." },
      { step: "Other biases", guidance: "Recall bias, selection bias, reverse causation, chance and multiple comparisons." },
      { step: "Better design", guidance: "Large prospective cohort; measure and adjust for smoking; stratify (non-smokers only); consider mechanism; RCT impractical and unethical over decades." },
      { step: "Conclude", guidance: "Association is not causation; look at the whole body of evidence." },
    ],
    exemplar:
      "My first questions would be about what kind of study it was. Was it an observational study that just found an association, or a trial? How many people were included, and how were coffee drinking and cancer measured — did people remember how much coffee they drank years ago? And how big was the increase — is it a large relative risk of a rare outcome, which might mean a very small absolute difference?\n\nThe biggest issue I'd suspect is confounding. Historically, people who drank a lot of coffee were more likely to smoke — the two often went together. Smoking causes lung cancer, so if the study didn't account for smoking properly, coffee could look like a cause when it's really just associated with the real cause.\n\nThere could also be other problems, like selection bias in who took part, or chance if the researchers tested lots of foods and one came up positive.\n\nTo investigate properly, a randomised trial — making some people drink coffee for decades — wouldn't be practical or ethical. So I'd design a large prospective cohort study: recruit people without cancer, record their coffee intake and smoking carefully, and follow them for many years. The key analysis would be looking at coffee and lung cancer only in people who have never smoked. If the association disappears in never-smokers, that suggests smoking was the explanation.\n\nI'd also want to know whether there's a plausible biological mechanism, and whether other studies found the same thing — one headline is rarely the full story.",
    annotations: [
      { excerpt: "a large relative risk of a rare outcome", note: "Understands the difference between relative and absolute risk." },
      { excerpt: "coffee could look like a cause when it's really just associated", note: "Clear explanation of confounding with a concrete confounder." },
      { excerpt: "only in people who have never smoked", note: "Elegant design solution — stratification to remove the confounder." },
    ],
    keyPoints: [
      "Study type, size and measurement questions.",
      "Confounding (smoking) explained clearly.",
      "Other biases and chance.",
      "Practical study design and stratification.",
      "Weight of evidence and mechanism.",
    ],
    pitfalls: [
      "Accepting the headline or dismissing it without reasoning.",
      "Proposing an unethical randomised trial.",
      "Using terms (confounding, bias) without explaining them.",
    ],
    frameworks: [{ slug: "data-interpretation-dqec", primary: true }, { slug: "thinking-aloud" }],
    reading: [],
    tags: ["critical-appraisal", "epidemiology", "research-methods"],
  },
  {
    slug: "is-a-virus-alive",
    category: "science-clinical-reasoning",
    formats: ["oxbridge"],
    difficulty: 4,
    universities: ["oxford", "cambridge"],
    question: "Is a virus alive?",
    whatIsBeingTested: "Ability to handle a question with no single correct answer: defining terms, testing definitions against cases, and reaching a reasoned position.",
    followUps: [
      "Is a seed alive? What about a red blood cell, which has no nucleus?",
      "Does it matter for medicine whether we call viruses alive?",
      "Could you design a definition of life that includes viruses but excludes crystals?",
    ],
    scaffold: [
      { step: "Define", guidance: "The answer depends on the definition of life — e.g. the characteristics listed at school (movement, respiration, sensitivity, growth, reproduction, excretion, nutrition), or 'a self-sustaining system capable of evolution'." },
      { step: "Test against viruses", guidance: "Viruses have genetic material and evolve, but no metabolism and can only replicate inside host cells." },
      { step: "Test the definition with other cases", guidance: "Red blood cells don't reproduce; seeds are dormant; obligate intracellular bacteria also depend on hosts." },
      { step: "Conclude", guidance: "Borderline; 'alive' may be a spectrum rather than binary; the definition is a human tool." },
    ],
    exemplar:
      "I think it depends on how we define 'alive', so I'd start there.\n\nAt school we learn characteristics like movement, respiration, growth, reproduction and so on. By that list, viruses mostly fail: outside a cell, a virus particle doesn't metabolise, grow or respond to anything — it's closer to a complex chemical. But once it's inside a host cell, it takes over the cell's machinery and makes thousands of copies of itself, and viruses carry genetic information and evolve by natural selection, which seems very life-like.\n\nThe trouble is that when I test the definition on other things, it wobbles. A red blood cell can't reproduce, but we'd say it's alive. A seed can be dormant for years with barely any metabolism. And some bacteria can only reproduce inside host cells too, yet we call them alive. So 'depends on a host' can't be the only dividing line.\n\nIf we use a definition like 'a system capable of evolution by natural selection', viruses would count. If we require independent metabolism, they don't.\n\nMy view is that viruses sit on the boundary, and that tells us something: 'alive' might be more of a spectrum than a yes/no category. The definition is a tool we invented, and viruses show its limits. For medicine, what matters more is understanding how they replicate — that's what we target with antivirals and vaccines.",
    annotations: [
      { excerpt: "it depends on how we define 'alive'", note: "Identifies that the question hinges on a definition — the key first move." },
      { excerpt: "when I test the definition on other things, it wobbles", note: "Tests the definition against counter-examples — philosophical rigour." },
      { excerpt: "more of a spectrum than a yes/no category", note: "A thoughtful conclusion that doesn't dodge the question." },
    ],
    keyPoints: [
      "Explicit definitions.",
      "Evidence for and against viruses fitting them.",
      "Counter-examples that test the definition.",
      "A reasoned conclusion.",
    ],
    pitfalls: [
      "A flat 'no' or 'yes' with one reason.",
      "Refusing to commit.",
      "Reciting MRS GREN without applying it.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["virology", "definitions", "oxbridge"],
  },
  {
    slug: "why-two-kidneys",
    category: "science-clinical-reasoning",
    formats: ["oxbridge", "panel"],
    difficulty: 3,
    universities: ["oxford", "cambridge"],
    question: "We can live perfectly well with one kidney. So why do we have two?",
    whatIsBeingTested: "Evolutionary reasoning, physiological reserve and the ability to challenge the premise of a question.",
    followUps: [
      "Why do we have only one heart?",
      "What happens to the remaining kidney after someone donates one?",
      "Is it ethical for a living person to donate a kidney?",
    ],
    scaffold: [
      { step: "Challenge the premise", guidance: "'Perfectly well' — true for most people at rest, but reserve matters under stress, injury or disease." },
      { step: "Reserve and redundancy", guidance: "Spare capacity protects against injury, infection and age-related decline; the remaining kidney increases its function (compensatory hypertrophy)." },
      { step: "Developmental explanation", guidance: "Bilateral symmetry: many paired organs arise from symmetrical development." },
      { step: "Evolutionary explanation", guidance: "Organs we can survive losing one of may have been selected for redundancy; cost of a second kidney is relatively low compared with the benefit." },
      { step: "Contrast", guidance: "Heart — a single pump works better; redundancy is only useful where a duplicate adds benefit." },
    ],
    exemplar:
      "I'd first question the word 'perfectly'. Most people who donate a kidney live healthy lives, but the second kidney gives us reserve: if one is injured, infected or blocked, or when kidney function declines with age or disease, having two provides a safety margin. After someone donates a kidney, the remaining one enlarges and increases its filtration, which suggests the body normally has spare capacity rather than needing both at full stretch.\n\nThere are a couple of different types of explanation. One is developmental: our bodies are built on a largely symmetrical plan, so many organs come in pairs — kidneys, lungs, eyes, ovaries — because they develop on both sides of the embryo. So the question could be 'why hasn't evolution got rid of one?' rather than 'why did we get two?'\n\nThe evolutionary answer might be that the extra kidney is relatively cheap to maintain, and the benefit — surviving an injury to one side, or an infection — could have been significant, especially before modern medicine.\n\nThe contrast with the heart is interesting. A second heart wouldn't simply be spare capacity; two pumps would have to coordinate, and the heart's structure already has four chambers doing different jobs. So redundancy seems to be kept where a duplicate genuinely adds safety at low cost.\n\nI'd want to know more about whether people with one kidney from birth have any different outcomes over a lifetime — that would tell us how much the reserve matters.",
    annotations: [
      { excerpt: "I'd first question the word 'perfectly'", note: "Challenges the premise — rewarded in Oxbridge interviews." },
      { excerpt: "There are a couple of different types of explanation", note: "Distinguishes developmental and evolutionary explanations — sophisticated." },
      { excerpt: "The contrast with the heart", note: "Tests the reasoning against a comparison case." },
      { excerpt: "I'd want to know more about", note: "Ends with a question that would test the hypothesis." },
    ],
    keyPoints: [
      "Physiological reserve and compensatory hypertrophy.",
      "Developmental symmetry.",
      "Evolutionary cost-benefit.",
      "Comparison with single organs.",
    ],
    pitfalls: [
      "Just saying 'in case one fails' with no depth.",
      "Accepting the premise without question.",
      "Stating that organ donation has no long-term risk.",
    ],
    frameworks: [{ slug: "thinking-aloud", primary: true }],
    reading: [],
    tags: ["physiology", "evolution", "renal", "oxbridge"],
  },
];
