import type { Question } from "../schema";

export const wildcardQuestions: Question[] = [
  {
    slug: "sell-me-this-pen",
    category: "wildcard",
    formats: ["mmi", "panel"],
    difficulty: 2,
    question: "Sell me this pen.",
    whatIsBeingTested: "Composure under an unexpected task, and — the hidden test — whether you ask about the other person's needs before talking (the same skill as a good consultation).",
    followUps: [
      "How does selling relate to being a doctor?",
      "What would you do if I said I didn't need a pen?",
      "Is it ever right for a doctor to 'sell' a treatment to a patient?",
    ],
    scaffold: [
      { step: "Pause and engage", guidance: "Smile, take the pen — treat it as a conversation, not a pitch." },
      { step: "Ask before telling", guidance: "What do they use pens for? What frustrates them about pens?" },
      { step: "Match features to needs", guidance: "Tailor benefits to their answers." },
      { step: "Handle objections honestly", guidance: "Don't oversell; respect a 'no'." },
      { step: "Reflect if invited", guidance: "Link to exploring patient needs and shared decision-making — and the difference between persuading and informing." },
    ],
    exemplar:
      "[Takes the pen, smiles.] \"Before I tell you anything about this pen — can I ask what you use a pen for most in your day?\"\n\n[Interviewer: 'Signing things, making notes in interviews like this.']\n\n\"And is there anything that annoys you about the pens you use now?\"\n\n[Interviewer: 'They run out, or they smudge.']\n\n\"OK — this one has a quick-drying ink, so no smudging on the forms you sign, and it's refillable, so it won't run out at the worst moment in the middle of an interview. It's also light enough to write for a long time without aching.\"\n\n[Interviewer: 'I've got loads of pens already.']\n\n\"That's fair — if the ones you have work well, you may not need it. But if you'd like one that doesn't smudge when you're signing things quickly, I think this one would suit you.\"\n\n[If invited to reflect:] \"I think the real skill was asking what you needed before telling you about the pen. It's similar to a consultation — you find out what matters to someone before offering options. Though as a doctor, the aim isn't to sell a treatment, but to help someone choose what's right for them — including choosing nothing.\"",
    annotations: [
      { excerpt: "Before I tell you anything about this pen", note: "The move that separates strong answers: ask before pitching." },
      { excerpt: "if the ones you have work well, you may not need it", note: "Respects the 'no' — honest rather than pushy." },
      { excerpt: "the aim isn't to sell a treatment", note: "Mature reflection that distinguishes persuasion from shared decision-making." },
    ],
    keyPoints: [
      "Composure and good humour.",
      "Questions before features.",
      "Tailoring to needs.",
      "Honest handling of objections.",
      "Reflective link to patient-centred care.",
    ],
    pitfalls: [
      "Freezing or refusing.",
      "A long monologue of features.",
      "High-pressure sales tactics.",
    ],
    frameworks: [{ slug: "ice", primary: true }],
    reading: [],
    tags: ["wildcard", "communication", "composure"],
  },
  {
    slug: "describe-yellow-to-blind-person",
    category: "wildcard",
    formats: ["mmi", "oxbridge"],
    difficulty: 3,
    question: "How would you describe the colour yellow to someone who has been blind from birth?",
    whatIsBeingTested: "Creativity, empathy for a different perspective, communication through analogy, and honesty about limits.",
    followUps: [
      "How would you know whether you had succeeded?",
      "How does this relate to explaining pain or symptoms?",
      "What are the limits of language in describing experience?",
    ],
    scaffold: [
      { step: "Acknowledge the challenge", guidance: "Colour can't be fully conveyed without sight; aim for associations." },
      { step: "Ask what they know", guidance: "Start from their experiences — sounds, textures, temperatures, emotions." },
      { step: "Use other senses and associations", guidance: "Warmth of sunlight, taste of lemon, feeling of energy." },
      { step: "Check understanding", guidance: "Ask what it evokes for them." },
      { step: "Reflect", guidance: "Link to communicating subjective experience in medicine (pain, symptoms)." },
    ],
    exemplar:
      "I'd start by being honest that I can't truly give someone the experience of seeing yellow — but I could try to share what it feels like to me through their other senses.\n\nI'd want to ask them first what they enjoy or know well, so I could build on that. But I might say: yellow is the colour of warmth on your face when you step outside on a sunny morning. It's the sharp, bright taste of lemon that makes you wake up. It's a cheerful, energetic colour — if it were a sound, it might be a trumpet rather than a cello. People use it for things that should catch your attention, because it feels bright and a bit loud.\n\nThen I'd ask them what those associations bring to mind for them, because their idea of yellow might be quite different from mine — and that's fine.\n\nI think this is similar to something doctors do all the time in reverse: patients try to describe pain or a strange sensation, and we can't feel it ourselves. It shows how much depends on finding shared reference points, and on checking you've understood rather than assuming.",
    annotations: [
      { excerpt: "I can't truly give someone the experience", note: "Honest framing of the limits." },
      { excerpt: "I'd want to ask them first", note: "Starts from the other person's experience — patient-centred instinct." },
      { excerpt: "if it were a sound, it might be a trumpet", note: "Creative cross-sensory analogy." },
      { excerpt: "in reverse: patients try to describe pain", note: "Insightful link to clinical communication." },
    ],
    keyPoints: [
      "Honesty about limits.",
      "Start from their experience.",
      "Multi-sensory, emotional associations.",
      "Check understanding.",
      "Link to describing subjective symptoms.",
    ],
    pitfalls: [
      "Visual descriptions ('like the sun') without translating.",
      "Freezing or dismissing the question.",
      "Being patronising.",
    ],
    frameworks: [{ slug: "chunk-and-check", primary: true }, { slug: "thinking-aloud" }],
    reading: [],
    tags: ["wildcard", "creativity", "communication"],
  },
  {
    slug: "health-secretary-for-a-day",
    category: "wildcard",
    formats: ["panel", "mmi"],
    difficulty: 3,
    question: "If you were Health Secretary for a day, what one change would you make to the NHS?",
    whatIsBeingTested: "Prioritisation, understanding of the health system, realism about implementation, and awareness of trade-offs.",
    followUps: [
      "How would you pay for it?",
      "Who might oppose your change?",
      "How would you know if it had worked?",
    ],
    scaffold: [
      { step: "Choose one change", guidance: "Specific and realistic (e.g. investment in social care to reduce delayed discharge; prevention; community services; staff wellbeing)." },
      { step: "Why", guidance: "Problem it solves, with evidence of scale or impact." },
      { step: "How", guidance: "Practical implementation." },
      { step: "Trade-offs", guidance: "Cost, opportunity cost, opposition, time to benefit." },
      { step: "Measure", guidance: "How you'd evaluate success." },
    ],
    exemplar:
      "I'd focus on social care — specifically, funding enough home care and rehabilitation so that people who are medically ready to leave hospital can do so safely.\n\nThe reason is that it affects the whole system. When patients who no longer need hospital care can't be discharged because there's no support at home, they take up beds. That means patients in A&E can't be admitted, ambulances wait outside, and planned operations get cancelled. It's also bad for the patients stuck in hospital — older people can lose strength and independence quickly lying in bed.\n\nIn practice, that would mean more funding for councils to pay care workers better — recruitment is difficult partly because care work is poorly paid — and joint teams between hospitals and councils to plan discharge early. Integrated care systems should in theory make that easier.\n\nThe trade-off is cost, and the money would have to come from somewhere — taxes, or other services. It also wouldn't produce results in a day: recruiting care staff takes time.\n\nI'd judge success by the number of patients waiting in hospital when they're ready to leave, A&E waiting times, and whether people discharged stay well at home rather than being readmitted.\n\nI'm aware it's a problem successive governments have promised to fix, which suggests it's harder than it sounds.",
    annotations: [
      { excerpt: "it affects the whole system", note: "Justifies the choice by its leverage across the system." },
      { excerpt: "older people can lose strength and independence", note: "Keeps the patient in view, not just system metrics." },
      { excerpt: "the money would have to come from somewhere", note: "Honest about trade-offs — avoids naive answers." },
      { excerpt: "I'd judge success by", note: "Defines measurable outcomes." },
    ],
    keyPoints: [
      "One well-chosen, specific change.",
      "Clear causal logic.",
      "Practical implementation.",
      "Honest trade-offs.",
      "Measurable outcomes.",
    ],
    pitfalls: [
      "'Give the NHS more money' with no detail.",
      "Party-political statements.",
      "Several changes superficially.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: ["nhs-structure-england", "ten-year-health-plan"],
    tags: ["wildcard", "policy", "social-care"],
  },
  {
    slug: "most-important-medical-advance",
    category: "wildcard",
    formats: ["panel", "oxbridge", "online"],
    difficulty: 3,
    question: "What do you think is the most important advance in the history of medicine?",
    whatIsBeingTested: "Breadth of interest, ability to define criteria for 'important', and reasoned argument.",
    followUps: [
      "Why not antibiotics?",
      "What advance do you think will be most important in the next 20 years?",
      "Are public health measures more important than medical treatments?",
    ],
    scaffold: [
      { step: "Define 'important'", guidance: "Lives saved? Quality of life? Enabling other advances? Reach?" },
      { step: "Choose one", guidance: "E.g. clean water/sanitation, germ theory, vaccination, antibiotics, anaesthesia, randomised controlled trials." },
      { step: "Justify", guidance: "Impact against your criteria; brief historical detail you're confident of." },
      { step: "Acknowledge alternatives", guidance: "Why others are strong contenders and why you still choose yours." },
    ],
    exemplar:
      "I think it depends on what we mean by 'important' — lives saved, or how much it enabled everything else. By both measures, I'd choose germ theory: the understanding that specific microorganisms cause specific diseases.\n\nBefore that, many people believed disease was caused by bad air or imbalance in the body, which made prevention and treatment largely guesswork. Work by people like Pasteur and Koch in the 19th century showed microbes caused disease, and that changed everything that came after. It explained why John Snow's removal of the Broad Street pump handle stopped a cholera outbreak, and it justified sanitation and clean water, which probably saved more lives than any single treatment. It underpins antiseptic surgery, vaccination as a science, and the search for antibiotics.\n\nThe obvious rivals are antibiotics and vaccines, which have directly saved enormous numbers of lives. But I'd see them as consequences of germ theory rather than alternatives to it.\n\nIf I had to pick something less obvious, I'd mention the randomised controlled trial, because it gave us a way to find out which treatments actually work — which is arguably just as foundational.",
    annotations: [
      { excerpt: "it depends on what we mean by 'important'", note: "Defines criteria before answering." },
      { excerpt: "I'd see them as consequences of germ theory", note: "Handles rivals with an argument rather than dismissing them." },
      { excerpt: "the randomised controlled trial", note: "Shows breadth and original thinking — but only if you can discuss it further." },
    ],
    keyPoints: [
      "Criteria defined.",
      "Clear choice with accurate supporting detail.",
      "Engagement with alternatives.",
      "Genuine curiosity.",
    ],
    pitfalls: [
      "Inaccurate history.",
      "A list with no choice.",
      "Choosing something you can't discuss further.",
    ],
    frameworks: [{ slug: "balanced-argument", primary: true }],
    reading: [],
    tags: ["wildcard", "history-of-medicine", "curiosity"],
  },
  {
    slug: "what-would-your-friends-say",
    category: "wildcard",
    formats: ["panel", "mmi", "online"],
    difficulty: 1,
    question: "How would your friends describe you — and what would they say is your most annoying habit?",
    whatIsBeingTested: "Self-awareness, authenticity and the ability to talk about yourself with honesty and a little humour.",
    followUps: [
      "Would your teachers describe you differently?",
      "Which of those qualities would help you most in medicine?",
      "What are you doing about the annoying habit?",
    ],
    scaffold: [
      { step: "Two or three qualities", guidance: "Brief, with a quick example each." },
      { step: "A genuine, harmless flaw", guidance: "Something real and relatable, not disqualifying." },
      { step: "Self-awareness", guidance: "What you're doing about it or how you manage it." },
      { step: "Stay natural", guidance: "Relaxed, warm, not over-polished." },
    ],
    exemplar:
      "I think they'd say I'm dependable and a good listener. I'm usually the person people message when something's gone wrong, and I'll happily spend an hour on the phone with someone who's had a bad day. They'd probably also say I'm quite competitive — I take our quiz team far too seriously.\n\nMy most annoying habit, according to them, is that I'm always slightly late for things that don't matter much — I'll turn up ten minutes late to meet for coffee, but never late for anything important. My friends have started telling me to meet them fifteen minutes earlier than they actually arrive.\n\nI'm genuinely working on it, because I've realised it sends a message that I don't value people's time, which isn't how I feel. I've started setting alarms for social things as well as work.\n\nI think the listening is the quality I'd most want to bring to medicine — though I'm aware being late won't be acceptable on a ward round!",
    annotations: [
      { excerpt: "I'm usually the person people message", note: "Shows a quality through behaviour rather than asserting it." },
      { excerpt: "My friends have started telling me to meet them fifteen minutes earlier", note: "Humour and authenticity — makes the candidate memorable." },
      { excerpt: "it sends a message that I don't value people's time", note: "Reflection on the impact of a flaw on others." },
    ],
    keyPoints: [
      "Qualities shown through examples.",
      "A real but harmless flaw.",
      "Reflection and action.",
      "Warmth and authenticity.",
    ],
    pitfalls: [
      "A 'flaw' that's a disguised strength.",
      "A flaw that suggests unprofessionalism in clinical settings, without reflection.",
      "Sounding rehearsed.",
    ],
    frameworks: [{ slug: "star" }],
    reading: [],
    tags: ["wildcard", "self-awareness"],
  },
];

export const questionsForThemQuestions: Question[] = [
  {
    slug: "do-you-have-any-questions-for-us",
    category: "questions-for-them",
    formats: ["panel", "oxbridge", "online"],
    difficulty: 1,
    question: "Do you have any questions for us?",
    whatIsBeingTested: "Genuine interest in the course, courtesy, and a composed, positive close.",
    followUps: [
      "(They may simply answer and close the interview.)",
      "Is there anything else you'd like to tell us about yourself?",
    ],
    scaffold: [
      { step: "Have one or two ready", guidance: "About learning, teaching, the student experience or an interviewer's own interests — things not easily answered on the website." },
      { step: "Keep it brief", guidance: "One question is plenty; don't interrogate." },
      { step: "It's fine to say no", guidance: "'I think you've covered everything, thank you' is acceptable — gracefully." },
      { step: "Close warmly", guidance: "Thank them for their time." },
    ],
    exemplar:
      "\"Yes, thank you. I read that students here do a research project in the later years. I was curious — what kinds of projects have students found most rewarding, and do they tend to shape what students go on to do?\"\n\n[Interviewer answers.]\n\n\"That's really interesting — thank you. And thank you both for your time today; I've really enjoyed the discussion, especially the kidney question.\"\n\n[Alternative if nothing comes to mind:] \"I think the website and today have answered most of my questions, thank you. I've really enjoyed the conversation.\"",
    annotations: [
      { excerpt: "I read that students here do a research project", note: "Shows prior research and genuine curiosity." },
      { excerpt: "what kinds of projects have students found most rewarding", note: "Invites the interviewer's perspective rather than a fact from the prospectus." },
      { excerpt: "especially the kidney question", note: "A light, genuine callback — ends on a positive, personal note." },
    ],
    keyPoints: [
      "One genuine, specific question.",
      "Not answerable from the website in seconds.",
      "Saying no gracefully is acceptable.",
      "Thank the interviewers.",
    ],
    pitfalls: [
      "Asking about your performance ('How did I do?').",
      "Questions about offers, grades or entry statistics.",
      "Several long questions when time is short.",
      "Questions whose answers are obvious on the website.",
    ],
    frameworks: [],
    reading: [],
    tags: ["closing", "questions-for-interviewers"],
  },
  {
    slug: "good-and-bad-questions-to-ask",
    category: "questions-for-them",
    formats: ["panel", "mmi", "online"],
    difficulty: 1,
    question: "Prepare three good questions you could ask at the end of an interview, and explain why each is a good one.",
    whatIsBeingTested: "Preparation exercise: thinking about what makes a question show curiosity and fit, and what to avoid.",
    followUps: [
      "Which question would you ask if you only had time for one?",
      "Why is asking 'How did I do?' a poor choice?",
    ],
    scaffold: [
      { step: "Learning and teaching", guidance: "E.g. how small-group teaching works in practice, or how students are supported in early clinical contact." },
      { step: "Student experience", guidance: "E.g. what distinguishes students who thrive here; opportunities in peer teaching, societies, widening participation work." },
      { step: "The interviewer's perspective", guidance: "E.g. what they enjoy about teaching here or how their field has changed." },
      { step: "Avoid", guidance: "Performance, offers, statistics, anything on the website, anything that sounds like a complaint." },
    ],
    exemplar:
      "First: 'What do you think distinguishes students who really thrive on this course?' — it shows I'm thinking about how to make the most of the course, and it invites an honest perspective.\n\nSecond: 'How do students get involved in teaching or mentoring younger students?' — it connects to something I enjoy and would contribute, and it's specific enough not to be answered by a prospectus.\n\nThird, if the interviewer is a clinician: 'What has changed most in your specialty since you trained?' — it's genuine curiosity, it's personal to them, and it often leads to a good conversation.\n\nI'd avoid asking how I did, or anything about offer statistics, because it puts the interviewer in an awkward position and suggests I'm focused on getting in rather than on the course.",
    annotations: [
      { excerpt: "distinguishes students who really thrive", note: "Forward-looking, positive question." },
      { excerpt: "connects to something I enjoy and would contribute", note: "Question doubles as evidence of fit." },
      { excerpt: "I'd avoid asking how I did", note: "Clear rationale for what not to ask." },
    ],
    keyPoints: [
      "Questions that show curiosity and fit.",
      "Specific, not prospectus-level.",
      "Respectful of interviewers' time.",
      "Know what to avoid and why.",
    ],
    pitfalls: [
      "Generic or website-answerable questions.",
      "Performance or offer questions.",
      "Too many questions.",
    ],
    frameworks: [],
    reading: [],
    tags: ["closing", "preparation"],
  },
  {
    slug: "anything-else-to-tell-us",
    category: "questions-for-them",
    formats: ["panel", "online"],
    difficulty: 2,
    question: "Is there anything else you would like to tell us that we haven't asked about?",
    whatIsBeingTested: "Ability to add something meaningful and concise — or to close gracefully — without repeating yourself.",
    followUps: [
      "Is there anything you feel you didn't get the chance to explain properly?",
      "What do you think you'd find hardest about starting medical school?",
    ],
    scaffold: [
      { step: "Decide quickly", guidance: "Is there something important about you that hasn't come up — an experience, context, or clarification of an earlier answer?" },
      { step: "Keep it to 30–45 seconds", guidance: "One point, clearly made." },
      { step: "Or close gracefully", guidance: "It's fine to say you've covered what you wanted to." },
      { step: "Thank them", guidance: "End warmly." },
    ],
    exemplar:
      "\"Thank you — just one thing. We didn't get to talk about my part-time job. I've worked at a supermarket for two years, often on Saturday mornings before my volunteering. It's taught me a lot about dealing calmly with frustrated customers and about managing my time, which I think will help with the demands of medicine.\"\n\n\"Otherwise, I think we've covered everything — thank you both very much for your time.\"",
    annotations: [
      { excerpt: "just one thing", note: "Signals brevity — respectful of time." },
      { excerpt: "dealing calmly with frustrated customers", note: "Adds a relevant, previously unmentioned quality with evidence." },
      { excerpt: "thank you both very much for your time", note: "Warm, gracious close." },
    ],
    keyPoints: [
      "One concise, relevant addition — or none.",
      "Something new, not a repeat.",
      "Gracious close.",
    ],
    pitfalls: [
      "A long speech repeating earlier answers.",
      "Trying to re-answer a question you felt went badly, at length.",
      "Pleading ('I really, really want this').",
    ],
    frameworks: [],
    reading: [],
    tags: ["closing"],
  },
];
