import type { Question } from "../schema";

export const workExperienceQuestions: Question[] = [
  {
    slug: "work-experience-what-did-you-learn",
    category: "work-experience-reflection",
    formats: ["mmi", "panel", "online"],
    difficulty: 2,
    question: "Tell me about your work experience. What did you learn from it?",
    whatIsBeingTested: "Ability to reflect — to turn observations into insight about patients, teams and yourself — rather than list what you did.",
    followUps: [
      "What surprised you most?",
      "Was there anything you saw that you disagreed with?",
      "How has it changed how you think about being a doctor?",
    ],
    scaffold: [
      { step: "Brief overview", guidance: "One sentence on where you went — don't list every placement." },
      { step: "What?", guidance: "Pick one specific moment and describe it briefly and anonymously." },
      { step: "So what?", guidance: "What it showed you — about patients, the team, the doctor's role, the NHS, or yourself." },
      { step: "Now what?", guidance: "How it has changed what you do or think. Concrete." },
    ],
    exemplar:
      "I spent a week in a GP surgery and have volunteered weekly at a care home for the past year. The moment that taught me most was at the care home.\n\nOne resident with dementia became very distressed every afternoon, asking to go home. I'd been trying to reassure her that this was her home now, which made her more upset. I noticed one carer did something different: instead of correcting her, she asked about the home she was thinking of — the garden, her husband — and within a few minutes the resident had calmed down and was smiling.\n\nWhat that showed me was that being factually right isn't always the most caring response. The carer was responding to the feeling behind the words — the need to feel safe — rather than the literal request. It also showed me how much expertise sits outside the medical team.\n\nSince then I've changed how I talk to residents: I ask more questions and correct less. I think that will matter in medicine, where patients often say one thing but are worried about another, and where listening for that is part of good care.",
    annotations: [
      { excerpt: "The moment that taught me most", note: "Chooses one event to go deep on instead of listing placements." },
      { excerpt: "I'd been trying to reassure her", note: "Honest about their own less effective approach — shows humility and makes the learning credible." },
      { excerpt: "being factually right isn't always the most caring response", note: "Genuine insight, clearly derived from the event." },
      { excerpt: "I've changed how I talk to residents", note: "Evidence of changed behaviour — the 'Now what' that most answers miss." },
    ],
    keyPoints: [
      "Depth over breadth: one moment, reflected on well.",
      "Insight that follows from what you actually observed.",
      "Recognition of the wider team's role.",
      "Evidence that it changed your behaviour.",
    ],
    pitfalls: [
      "Listing departments and procedures seen.",
      "Clinical showing-off ('I saw a Whipple's procedure').",
      "Identifiable patient details.",
      "Generic lessons ('I learned communication is important').",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }, { slug: "gibbs-reflective-cycle" }],
    reading: ["being-mortal", "nhs-constitution"],
    tags: ["reflection", "work-experience", "dementia", "communication"],
  },
  {
    slug: "no-clinical-work-experience",
    category: "work-experience-reflection",
    formats: ["panel", "mmi"],
    difficulty: 3,
    question: "You haven't been able to shadow doctors in a hospital. How can you be sure medicine is right for you?",
    whatIsBeingTested: "Whether you have found other meaningful ways to understand medicine, and can reflect maturely without being defensive.",
    followUps: [
      "What do you think you've missed by not shadowing?",
      "What did you do instead?",
      "How did you find out what a doctor's day is really like?",
    ],
    scaffold: [
      { step: "Acknowledge without apology", guidance: "Shadowing isn't the only route — medical schools value caring experience and insight." },
      { step: "What you did instead", guidance: "Volunteering, caring roles, virtual work experience, talking to doctors, reading, a caring responsibility at home." },
      { step: "What it taught you", guidance: "Specific insight about patients, caring, the NHS — and yourself." },
      { step: "Honest limits", guidance: "Say what you haven't seen and how you've tried to understand it." },
    ],
    exemplar:
      "That's a fair question. Hospital placements were hard to get where I live, so I focused on experiences where I'd be doing something useful rather than only observing.\n\nFor the past eighteen months I've volunteered on a hospice ward's tea round and at a local food bank. At the hospice I've spent a lot of time simply sitting with patients and families. It taught me that a lot of care is presence rather than intervention, and it showed me how palliative care teams — doctors, nurses, chaplains — work together around what the patient wants.\n\nTo understand the doctor's role specifically, I completed the RCGP's online work experience programme and spoke at length with a GP who's a family friend about her week — including the admin and the decisions she carries home. I also read Being Mortal, which made me think about how doctors decide when more treatment isn't better.\n\nI know I haven't seen the pace of an acute ward or the intensity of a theatre list, and I'm not going to pretend otherwise. But what I've seen is that I can stay with people in difficult moments, and that I find the questions doctors face fascinating. That's given me confidence this is the right path — with a realistic sense of what I still have to learn.",
    annotations: [
      { excerpt: "I focused on experiences where I'd be doing something useful", note: "Reframes positively without being defensive." },
      { excerpt: "a lot of care is presence rather than intervention", note: "Insight rooted in sustained caring experience — valued highly by most schools." },
      { excerpt: "I'm not going to pretend otherwise", note: "Honesty about the gap increases credibility." },
    ],
    keyPoints: [
      "Medical schools do not require hospital shadowing; caring experience and insight count.",
      "Specific alternatives and what each taught you.",
      "Understanding of the doctor's role gained through conversation, reading or virtual programmes.",
      "Honest acknowledgement of limits.",
    ],
    pitfalls: [
      "Apologising repeatedly or sounding defensive.",
      "Overclaiming insight from a short online course.",
      "Blaming others for lack of opportunities.",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }],
    reading: ["being-mortal"],
    tags: ["work-experience", "widening-participation", "caring-experience"],
  },
  {
    slug: "observed-poor-practice",
    category: "work-experience-reflection",
    formats: ["mmi", "panel"],
    difficulty: 4,
    question: "Did you see anything during your work experience that you thought could have been done better?",
    whatIsBeingTested: "Critical observation balanced with fairness and professionalism — and understanding of how to raise concerns appropriately.",
    followUps: [
      "Did you say anything at the time?",
      "What would you do if you saw something similar as a medical student?",
      "Why might the staff member have acted that way?",
    ],
    scaffold: [
      { step: "Choose carefully", guidance: "A genuine but proportionate example — communication, dignity, teamwork. Avoid something so serious you should have reported it." },
      { step: "Describe fairly", guidance: "Anonymous, factual, without blame." },
      { step: "Consider context", guidance: "Why it might have happened: workload, system pressures, information you didn't have." },
      { step: "What better looks like", guidance: "What could have been done differently and how you'd act." },
      { step: "Raising concerns", guidance: "How a student should raise a concern: a supervisor or tutor, using proper routes." },
    ],
    exemplar:
      "Yes — on a busy medical ward I saw a doctor deliver test results to a patient from the foot of the bed, standing, while the curtain was half open and the patient in the next bed could clearly hear. The patient looked uncomfortable and didn't ask any questions.\n\nI don't think the doctor was uncaring — the ward was very stretched that morning and she had a long list. But it made me think about how privacy and dignity can slip under time pressure, and that small changes like closing the curtain, sitting down and asking 'Is now a good time?' take seconds and change how information is received.\n\nAs a work-experience student I didn't feel it was my place to comment in the moment, and I don't think it was a safety issue. I did mention it afterwards to the consultant supervising me, framed as a question about how doctors protect privacy on open wards. She said it was a common problem and pointed out the ward's side room was usually used for difficult news.\n\nAs a medical student, if I saw something that affected a patient's safety or dignity, I'd raise it with my supervisor or through the school's concern process — Good Medical Practice is clear that patient safety comes before worrying about awkwardness.",
    annotations: [
      { excerpt: "I don't think the doctor was uncaring", note: "Fairness and context before criticism — essential in this question." },
      { excerpt: "take seconds", note: "Shows the fix is practical, not idealistic." },
      { excerpt: "framed as a question", note: "Mature way to raise a minor concern as a student." },
      { excerpt: "patient safety comes before worrying about awkwardness", note: "Knows the professional duty — could name the specific route (e.g. Freedom to Speak Up Guardian) for extra depth." },
    ],
    keyPoints: [
      "A proportionate example described without blame.",
      "Consideration of system and workload factors.",
      "What good practice would have looked like.",
      "Appropriate routes for raising concerns and the duty to do so.",
    ],
    pitfalls: [
      "Harsh criticism of named or identifiable staff.",
      "Describing something serious you did nothing about.",
      "Claiming you would have intervened directly in clinical care.",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }, { slug: "ethical-dilemma-structure" }],
    reading: ["gmc-good-medical-practice", "francis-report"],
    tags: ["reflection", "raising-concerns", "dignity"],
  },
  {
    slug: "caring-experience-learned-about-yourself",
    category: "work-experience-reflection",
    formats: ["mmi", "online", "panel"],
    difficulty: 2,
    question: "What has your volunteering or caring experience taught you about yourself?",
    whatIsBeingTested: "Self-awareness and honest reflection on personal strengths and limitations shown through sustained caring experience.",
    followUps: [
      "What did you find hardest?",
      "Was there a time you didn't know what to do?",
      "How will this help you as a medical student?",
    ],
    scaffold: [
      { step: "Context", guidance: "Brief: what, where, how long. Sustained commitment matters." },
      { step: "A strength confirmed", guidance: "With a specific example." },
      { step: "A limitation discovered", guidance: "Honest, with what you did about it." },
      { step: "Forward link", guidance: "How it prepares you for medicine." },
    ],
    exemplar:
      "I've volunteered at a youth club for children with additional needs every Saturday for two years.\n\nIt's shown me I'm patient in a way I didn't expect. One boy with autism would only join in if the routine was exactly the same each week, and for a while I found that frustrating. Over time I learned to plan around it — telling him about changes in advance, using the same phrases — and eventually he joined the group games. That taught me patience is less about waiting and more about adapting to someone else's needs.\n\nIt also showed me a limitation: I find it hard not to take things personally. When a parent once complained that I'd let their daughter get upset, I dwelled on it all week. Talking it through with the club leader helped me see that the parent was anxious rather than attacking me, and that it was useful feedback. I've since tried to separate the message from the emotion when I get criticism.\n\nBoth of those feel relevant to medicine, where you adapt to every patient and where you'll regularly get difficult feedback — sometimes from people who are frightened.",
    annotations: [
      { excerpt: "every Saturday for two years", note: "Sustained commitment signalled in one phrase." },
      { excerpt: "patience is less about waiting and more about adapting", note: "A reflective reframing, not a claimed virtue." },
      { excerpt: "I find it hard not to take things personally", note: "Real limitation with evidence of work on it — highly credible." },
    ],
    keyPoints: [
      "Sustained, genuine commitment.",
      "A strength shown through an example.",
      "An honest limitation and what you're doing about it.",
      "Clear link to medicine.",
    ],
    pitfalls: [
      "Only strengths — no genuine self-reflection.",
      "Describing activities rather than what you learned about yourself.",
      "Patronising language about the people you support.",
    ],
    frameworks: [{ slug: "what-so-what-now-what", primary: true }, { slug: "star" }],
    reading: [],
    tags: ["reflection", "caring-experience", "self-awareness"],
  },
  {
    slug: "patient-encounter-that-stayed-with-you",
    category: "work-experience-reflection",
    formats: ["panel", "mmi"],
    difficulty: 3,
    question: "Tell me about a patient or person you met during your experience who has stayed with you.",
    whatIsBeingTested: "Empathy, emotional maturity and the ability to reflect on a human encounter while maintaining confidentiality.",
    followUps: [
      "How did it make you feel?",
      "How would you cope if you met many patients like that as a doctor?",
      "What did the professionals do well?",
    ],
    scaffold: [
      { step: "Introduce the person anonymously", guidance: "Enough detail to make them real, nothing identifiable." },
      { step: "What happened and what you noticed", guidance: "Focus on the human side as well as the medical." },
      { step: "Feelings", guidance: "How it affected you — honestly." },
      { step: "Meaning", guidance: "What it taught you about patients, illness, care or yourself." },
    ],
    exemplar:
      "On my hospice placement I met a man in his sixties who'd been a carpenter. He was very frail, but every day he asked for the window to be opened so he could hear the builders on the site next door.\n\nWhat stayed with me was a conversation I overheard between him and one of the palliative care doctors. He asked whether he'd be able to go home. She didn't say yes or no immediately — she asked him what 'home' would mean to him and what he was hoping for. It turned out he mostly wanted to see his workshop once more. The team arranged for his son to bring photos and some of his tools in, and he talked about them for days.\n\nI felt sad, because it was clear he wasn't going to get better, but I also felt something I didn't expect, which was that his last weeks had real meaning because people had listened to what mattered to him.\n\nIt changed how I think about the goal of medicine. I used to see it as curing people, but that doctor was treating him skilfully without any possibility of cure — by finding out what mattered and working towards that.",
    annotations: [
      { excerpt: "every day he asked for the window to be opened", note: "A humanising, non-identifying detail that makes the story vivid." },
      { excerpt: "asked him what 'home' would mean to him", note: "Observes a real communication skill — exploring expectations." },
      { excerpt: "I felt sad… but I also felt", note: "Emotional honesty and maturity." },
      { excerpt: "It changed how I think about the goal of medicine", note: "Insight connected to palliative care — link to Being Mortal if asked what you've read." },
    ],
    keyPoints: [
      "Confidentiality maintained.",
      "Attention to the person, not just the condition.",
      "Honest emotional response.",
      "A meaningful, well-articulated insight.",
    ],
    pitfalls: [
      "Identifying details (names, rare conditions plus location).",
      "Using the patient as a prop for a story about yourself.",
      "Over-dramatising or claiming involvement in clinical decisions.",
    ],
    frameworks: [{ slug: "gibbs-reflective-cycle", primary: true }, { slug: "ice" }],
    reading: ["being-mortal", "when-breath-becomes-air"],
    tags: ["reflection", "palliative-care", "empathy"],
  },
];
