-- Generated by scripts/build-seed.ts. Do not edit by hand.
begin;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$jehovahs-witness-refuses-blood$c$) where slug = $c$four-pillars$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$epilepsy-patient-still-driving$c$) where slug = $c$ethical-dilemma-structure$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$why-medicine$c$) where slug = $c$why-medicine-meif$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$teamwork-example$c$) where slug = $c$star$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$vaccination-uptake-graph$c$) where slug = $c$data-interpretation-dqec$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$should-doctors-strike$c$) where slug = $c$balanced-argument$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$estimate-heartbeats-lifetime$c$) where slug = $c$thinking-aloud$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$work-experience-what-did-you-learn$c$) where slug = $c$what-so-what-now-what$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$tell-me-about-a-mistake$c$) where slug = $c$gibbs-reflective-cycle$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$role-play-lost-laptop$c$) where slug = $c$spikes$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$role-play-patient-stopped-medication$c$) where slug = $c$ice$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$explain-asthma-inhaler$c$) where slug = $c$chunk-and-check$c$;
update interview.frameworks set worked_example_question_id = (select id from interview.questions where slug = $c$role-play-angry-relative$c$) where slug = $c$de-escalation$c$;
commit;
